FROM ubuntu:latest

WORKDIR /app

# Install curl for healthcheck and debugging
RUN apt-get update && apt-get install -y \
    libc6 \
    libstdc++6 \
    curl \
    && rm -rf /var/lib/apt/lists/*



# Copy the native executable from builder stage
COPY ./wfprev-api /app/

RUN chmod -x /app/wfprev-api

# Expose the port your application uses
EXPOSE 8080

RUN chmod +x /app/wfprev-api

ENTRYPOINT ["/app/wfprev-api"]