FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

# Copy the built jar from the host
COPY target/*.jar app.jar

# Expose port and debug port
EXPOSE 8080 5005

# Run the application
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "app.jar"]
