/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 02-Jun-2025 4:00:17 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."project_obj_filter_summ"
(
	"project_obj_filter_summ_guid" UUID NOT NULL,    -- project_obj_filter_summ_guid is a unique identifier for the record.
	"project_guid" UUID NOT NULL,    -- project_guid: Is a foreign key to project: Project is used to track Prevention Projects which are created to reduce risks due to forest fires. 
	"wui_risk_class_code" varchar(10)	 NULL,    -- wui_risk_class_code: Is a foreign key to wui_risk_class_code: Wildland Urban Interface Risk Class Code are the set of code used to assess the risk of wildfires interfacing with urban environments.  Values are:   	- WUI RC 1 	- WUI RC 2 	- WUI RC 3 	- WUI RC 4 	- WUI RC 5
	"local_wui_risk_class_code" varchar(10)	 NULL,    -- local_wui_risk_class_code: Is a foreign key to wui_risk_class_code: Wildland Urban Interface Risk Class Code are the set of code used to assess the risk of wildfires interfacing with urban environments.  Values are:   	- WUI RC 1 	- WUI RC 2 	- WUI RC 3 	- WUI RC 4 	- WUI RC 5
	"wui_risk_class_comment" varchar(4000)	 NULL,    -- Wildland Urban Interface Risk Class Comment are general comments regarding the Wildland Urban Interface Risk Class.
	"local_wui_risk_class_rationale" varchar(4000)	 NULL,    -- Local Wildland Urban Interface Risk Class Rationale allows staff to record a rationale for assessing risk class for project.
	"coarse_filter_score" INT NOT NULL,    -- Coarse Filter Score is a score calculated by summing the weighted ranks of coarse filter objectives that are selected as being aligned for the project.
	"coarse_filter_comment" varchar(4000)	 NULL,    -- Coarse Filter Comment contains the rationale or additional comments regarding the coarse filters for the project.
	"government_obj_align_score" decimal(5) NOT NULL DEFAULT 0,    -- Medium Filter Score is a score calculated by summing the weighted ranks of medium filter objectives that are selected as being aligned for the project
	"medium_filter_comment" varchar(4000)	 NULL,    -- Medium Filter Comment contains the rationale or additional comments regarding the medium filters for the project.  For example, the Fuel Management medium filter comment could contain additional comments/notes on government alignment objectives associated to the fuel management request.
	"fine_filter_score" decimal(5) NOT NULL DEFAULT 0,    -- Fine Filter Score is a score calculated by summing the weighted ranks of fine filter objectives that are selected as being aligned for the project.
	"fine_filter_comment" varchar(4000)	 NULL,    -- Fine Filter Comment contains the rationale or additional comments regarding the fine filters for the project.  For example, the fuel management fine filter comment could contain additional comments/notes on project level objectives associated to the fuel management request.
	"total_filter_score" decimal(5) NOT NULL DEFAULT 0,    -- Total Filter Score is the sum of the Coarse filter, Medium Filter Score and the Fine Filter Scores.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."project_obj_filter_summ"
	IS 'Project Objective Filter Summary summarizes project filters which are used to evaluate objectives to be accomplished by a project.   Project objective filters are used to rank and prioritize projects.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."project_obj_filter_summ_guid"
	IS 'project_obj_filter_summ_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."project_guid"
	IS 'project_guid: Is a foreign key to project: Project is used to track Prevention Projects which are created to reduce risks due to forest fires. '
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."wui_risk_class_code"
	IS 'wui_risk_class_code: Is a foreign key to wui_risk_class_code: Wildland Urban Interface Risk Class Code are the set of code used to assess the risk of wildfires interfacing with urban environments.  Values are:   	- WUI RC 1 	- WUI RC 2 	- WUI RC 3 	- WUI RC 4 	- WUI RC 5'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."local_wui_risk_class_code"
	IS 'local_wui_risk_class_code: Is a foreign key to wui_risk_class_code: Wildland Urban Interface Risk Class Code are the set of code used to assess the risk of wildfires interfacing with urban environments.  Values are:   	- WUI RC 1 	- WUI RC 2 	- WUI RC 3 	- WUI RC 4 	- WUI RC 5'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."wui_risk_class_comment"
	IS 'Wildland Urban Interface Risk Class Comment are general comments regarding the Wildland Urban Interface Risk Class.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."local_wui_risk_class_rationale"
	IS 'Local Wildland Urban Interface Risk Class Rationale allows staff to record a rationale for assessing risk class for project.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."coarse_filter_score"
	IS 'Coarse Filter Score is a score calculated by summing the weighted ranks of coarse filter objectives that are selected as being aligned for the project.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."coarse_filter_comment"
	IS 'Coarse Filter Comment contains the rationale or additional comments regarding the coarse filters for the project.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."government_obj_align_score"
	IS 'Medium Filter Score is a score calculated by summing the weighted ranks of medium filter objectives that are selected as being aligned for the project'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."medium_filter_comment"
	IS 'Medium Filter Comment contains the rationale or additional comments regarding the medium filters for the project.  For example, the Fuel Management medium filter comment could contain additional comments/notes on government alignment objectives associated to the fuel management request.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."fine_filter_score"
	IS 'Fine Filter Score is a score calculated by summing the weighted ranks of fine filter objectives that are selected as being aligned for the project.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."fine_filter_comment"
	IS 'Fine Filter Comment contains the rationale or additional comments regarding the fine filters for the project.  For example, the fuel management fine filter comment could contain additional comments/notes on project level objectives associated to the fuel management request.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."total_filter_score"
	IS 'Total Filter Score is the sum of the Coarse filter, Medium Filter Score and the Fine Filter Scores.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."project_obj_filter_summ"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."project_obj_filter_summ" ADD CONSTRAINT "pofs_pk"
	PRIMARY KEY ("project_obj_filter_summ_guid")
;

ALTER TABLE "wfprev"."project_obj_filter_summ" ADD CONSTRAINT "pofs_uk" UNIQUE ("project_guid")
;

CREATE INDEX "pofs_wuirccd_idx" ON "wfprev"."project_obj_filter_summ" ("wui_risk_class_code" ASC)
;

CREATE INDEX "pofs_wuirccd_local_idx" ON "wfprev"."project_obj_filter_summ" ("local_wui_risk_class_code" ASC)
;

CREATE INDEX "pofs_prjct_idx" ON "wfprev"."project_obj_filter_summ" ("project_guid" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfprev"."project_obj_filter_summ" ADD CONSTRAINT "pofs_wuirccd_fk"
	FOREIGN KEY ("wui_risk_class_code") REFERENCES "wfprev"."wui_risk_class_code" ("wui_risk_class_code") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "wfprev"."project_obj_filter_summ" ADD CONSTRAINT "pofs_wuirccd_local_fk"
	FOREIGN KEY ("local_wui_risk_class_code") REFERENCES "wfprev"."wui_risk_class_code" ("wui_risk_class_code") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "wfprev"."project_obj_filter_summ" ADD CONSTRAINT "pofs_prjct_fk"
	FOREIGN KEY ("project_guid") REFERENCES "wfprev"."project" ("project_guid") ON DELETE No Action ON UPDATE No Action
;