/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 02-Jun-2025 4:00:17 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."project_objective"
(
	"project_objective_guid" UUID NOT NULL,    -- project_objective_guid is a unique identifier for the record.
	"objective_label" varchar(300)	 NOT NULL,    -- Objective Label is a brief statement of a fire prevention objective.
	"system_start_timestamp" TIMESTAMP NOT NULL,    -- System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"system_end_timestamp" TIMESTAMP NOT NULL,    -- System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"objective_filter_level_code" varchar(10)	 NOT NULL,    -- objective_filter_level_code: Is a foreign key to objective_filter_level_code: Objective Filter Level Code defines a set of filter levels that an objective can be defined for:  Values are:  	- Coarse Filter 	- Medium Filter 	- Fine Filter
	"project_type_code" varchar(10)	 NOT NULL,    -- project_type_code: Is a foreign key to project_type_code: Project Type Code defines the type of the project.  Values are:   	- Fuel Management  	- Cultural & Prescribed Fire
	"weighted_rank" decimal(5,2) NOT NULL,    -- Weighted Rank is a rank assigned to an objective. Every objective has a rank, and that rank is weighted.  No two objectives have the same weighted rank. The current weighted ranks range from 1 (lowest rank) to 12 (highest rank).
	"display_order" decimal(5) NOT NULL DEFAULT 0,    -- Display Order is the order in which the objectives should be displayed in an interface.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."project_objective"
	IS 'Project Objective is a set of ranked objectives that can be associated to a Project.  The objectives are broken into categories, such as project alignment with government objectives and project level objectives.  The objectives are ranked by importance. A project will receive a project alignment score for each objective category which is used to rank the importance of a project.  Government Alignment Objectives are: 12 - Treatment with several TUs moving onto next Unit 11 - Adjacent Fuel Management Treatments, or new TU with Rx 10 - Prescription Complete - Next phase is treatment 9 - Tactical Plan Complete - New Phase Rx Development 8 - Mitigates Risk around or adjacent to Critical Infrastructure incl Watersheds 7 - Improve Egress/Evac Routes 6 - Maximize Funding Linkages 5 - Supports Reconciliation with Indigenous peoples  Project Levels Objectives are: 4 - PSTA Class Greater than 7 3 - Part of Larger Risk Reduction Strategy 2 - Cost Effectiveness 1 - WUI WRR Plans with AOI that expands outside of the WUI'
;

COMMENT ON COLUMN "wfprev"."project_objective"."project_objective_guid"
	IS 'project_objective_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."project_objective"."objective_label"
	IS 'Objective Label is a brief statement of a fire prevention objective.'
;

COMMENT ON COLUMN "wfprev"."project_objective"."system_start_timestamp"
	IS 'System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."project_objective"."system_end_timestamp"
	IS 'System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."project_objective"."objective_filter_level_code"
	IS 'objective_filter_level_code: Is a foreign key to objective_filter_level_code: Objective Filter Level Code defines a set of filter levels that an objective can be defined for:  Values are:  	- Coarse Filter 	- Medium Filter 	- Fine Filter'
;

COMMENT ON COLUMN "wfprev"."project_objective"."project_type_code"
	IS 'project_type_code: Is a foreign key to project_type_code: Project Type Code defines the type of the project.  Values are:   	- Fuel Management  	- Cultural & Prescribed Fire'
;

COMMENT ON COLUMN "wfprev"."project_objective"."weighted_rank"
	IS 'Weighted Rank is a rank assigned to an objective. Every objective has a rank, and that rank is weighted.  No two objectives have the same weighted rank. The current weighted ranks range from 1 (lowest rank) to 12 (highest rank).'
;

COMMENT ON COLUMN "wfprev"."project_objective"."display_order"
	IS 'Display Order is the order in which the objectives should be displayed in an interface.'
;

COMMENT ON COLUMN "wfprev"."project_objective"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."project_objective"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."project_objective"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."project_objective"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."project_objective"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."project_objective" ADD CONSTRAINT "prjobj_pk"
	PRIMARY KEY ("project_objective_guid")
;

ALTER TABLE "wfprev"."project_objective" ADD CONSTRAINT "prjobj_uk" UNIQUE ("objective_label","system_start_timestamp","system_end_timestamp")
;

CREATE INDEX "prjobj_oflcd_idx" ON "wfprev"."project_objective" ("objective_filter_level_code" ASC)
;

CREATE INDEX "prjobj_prjtcd_idx" ON "wfprev"."project_objective" ("project_type_code" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfprev"."project_objective" ADD CONSTRAINT "prjobj_oflcd_fk"
	FOREIGN KEY ("objective_filter_level_code") REFERENCES "wfprev"."objective_filter_level_code" ("objective_filter_level_code") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "wfprev"."project_objective" ADD CONSTRAINT "prjobj_prjtcd_fk"
	FOREIGN KEY ("project_type_code") REFERENCES "wfprev"."project_type_code" ("project_type_code") ON DELETE No Action ON UPDATE No Action
;