/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 02-Jun-2025 4:43:05 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."wui_risk_class_rank"
(
	"wui_risk_class_rank_guid" UUID NOT NULL,    -- wui_risk_class_rank_guid is a unique identifier for the record.
	"wui_risk_class_code" varchar(10)	 NOT NULL,    -- wui_risk_class_code: Is a foreign key to wui_risk_class_code: Wildland Urban Interface Risk Class Code are the set of code used to assess the risk of wildfires interfacing with urban environments.  Values are:   	- WUI RC 1 	- WUI RC 2 	- WUI RC 3 	- WUI RC 4 	- WUI RC 5
	"system_start_timestamp" TIMESTAMP NOT NULL,    -- System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"system_end_timestamp" TIMESTAMP NOT NULL,    -- System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"weighted_rank" decimal(5,2) NOT NULL,    -- Weighted Rank is a rank assigned to an objective. Every objective has a rank, and that rank is weighted.  No two objectives have the same weighted rank. The current weighted ranks range from 1 (lowest rank) to 12 (highest rank).
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."wui_risk_class_rank"
	IS 'WUI Risk Class Rank is used to store the weighted rankings for each WUI Risk Class Code.  For example:  WUI Risk Class 1 = 10 Points WUI Risk Class 2 = 8 Points  WUI Risk Class 3 = 6 Points  WUI Risk Class 4 = 4 Points WUI Risk Class 5 = 2 Points '
;

COMMENT ON COLUMN "wfprev"."wui_risk_class_rank"."wui_risk_class_rank_guid"
	IS 'wui_risk_class_rank_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."wui_risk_class_rank"."wui_risk_class_code"
	IS 'wui_risk_class_code: Is a foreign key to wui_risk_class_code: Wildland Urban Interface Risk Class Code are the set of code used to assess the risk of wildfires interfacing with urban environments.  Values are:   	- WUI RC 1 	- WUI RC 2 	- WUI RC 3 	- WUI RC 4 	- WUI RC 5'
;

COMMENT ON COLUMN "wfprev"."wui_risk_class_rank"."system_start_timestamp"
	IS 'System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."wui_risk_class_rank"."system_end_timestamp"
	IS 'System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."wui_risk_class_rank"."weighted_rank"
	IS 'Weighted Rank is a rank assigned to an objective. Every objective has a rank, and that rank is weighted.  No two objectives have the same weighted rank. The current weighted ranks range from 1 (lowest rank) to 12 (highest rank).'
;

COMMENT ON COLUMN "wfprev"."wui_risk_class_rank"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."wui_risk_class_rank"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."wui_risk_class_rank"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."wui_risk_class_rank"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."wui_risk_class_rank"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."wui_risk_class_rank" ADD CONSTRAINT "wujircr_pk"
	PRIMARY KEY ("wui_risk_class_rank_guid")
;

ALTER TABLE "wfprev"."wui_risk_class_rank" ADD CONSTRAINT "wujircr_uk" UNIQUE ("wui_risk_class_code","system_start_timestamp","system_end_timestamp")
;

CREATE INDEX "wujircr_wuirccd_idx" ON "wfprev"."wui_risk_class_rank" ("wui_risk_class_code" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfprev"."wui_risk_class_rank" ADD CONSTRAINT "wujircr_wuirccd_fk"
	FOREIGN KEY ("wui_risk_class_code") REFERENCES "wfprev"."wui_risk_class_code" ("wui_risk_class_code") ON DELETE No Action ON UPDATE No Action
;