/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 13-Jan-2026 4:59:05 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."project_plan_fiscal_perf_audit"
(
	"audit_table_sequence" decimal(15) NOT NULL,    -- Added by transform - intent is make this sequence noncached so order is maintained
	"audit_action_code" varchar(10)	 NOT NULL,    -- Contains the reason the audit record is written - Insert/Update/Delete/Conversion
	"project_plan_fiscal_perf_guid" UUID NULL,    -- project_plan_fiscal_perf_guid is a unique identifier for the record.
	"project_plan_fiscal_guid" UUID NOT NULL,    -- project_plan_fiscal_guid: Is a foreign key to project_plan_fiscal: Project Plan Fiscal is used to store a plan for the work to be done in a fiscal year for the project. 
	"submitted_timestamp" TIMESTAMP NOT NULL,    -- Submitted Timestamp is the date and time the performance update was entered.
	"progress_status_code" varchar(10)	 NULL,    -- progress_status_code: Is a foreign key to progress_status_code: Progress Status Code tracks the progress for a fiscal project. Values are:  	- On Track 	- Deferred 	- Delayed 	- Cancelled
	"plan_fiscal_status_code" varchar(10)	 NOT NULL,    -- plan_fiscal_status_code: Is a foreign key to plan_fiscal_status_code: Plan Fiscal Status Code is the set of statuses a project plan may transition through. Values are:  	- Draft 	- Proposed 	- Prepared 	- In Progress 	- Complete 	- Abandoned
	"reporting_period_code" varchar(10)	 NOT NULL,    -- reporting_period_code: Is a foreign key to reporting_period_code: Reporting Period Code is a list of reporting periods that performance updates can be provided for. Values:  	- Q1 - End of First Quarter 	- Q2 - End of Second Quarter 	- Q3 - End of Third Quarter 	- Q4 - End of Fourth Quarter 	- CUSTOM - Other
	"submitted_by_name" varchar(100)	 NOT NULL,    -- Submitted By Name is the display name of the person who entered the performance update.
	"submitted_by_userid" varchar(64)	 NULL,    -- Submitted By Userid is the IDIR or BCEID userid of the user that created the performance update.   The client has a business requirement to display the Userid of the user in their application interfaces.
	"submitted_by_guid" varchar(36)	 NULL,    -- Submitted By Guid is the user GUID identifying the person who created the performance update.   The user guid is stored in this field corresponds to a user authorized in the WebADE platform.
	"previous_forecast_amount" decimal(15,2) NULL DEFAULT 0,    -- Previous Forecast Amount is the amount that was previously forecast. It is set to the Project Plan Fiscal forecast amount if the forecast amount is greater than zero, otherwise it is set to the Project Plan Fiscal Total Cost Estimate Amount. 
	"forecast_amount" decimal(15,2) NOT NULL DEFAULT 0,    -- Forecast Amount is the total amount the project lead reports will be spent (encumberances and actuals) for the period.
	"forecast_adjustment_amount" decimal(15,2) NOT NULL DEFAULT 0,    -- Forecast Adjustment Amount is difference between the previous forecast amount and the current forecast amount
	"forecast_adjustment_rationale" varchar(4000)	 NOT NULL,    -- Forecast Adjustment Rationale is a rationale provided to justify the adjusted forecast.
	"general_update_comment" varchar(4000)	 NOT NULL,    -- General Update Comment is free-form text providing additional detail regarding the successes, challenges, and progress made.
	"budget_high_risk_amount" decimal(15,2) NULL,    -- Budget High Risk Amount is the portion of the budget that has been identified as high risk.
	"budget_high_risk_rationale" varchar(4000)	 NULL,    -- Budget High Risk Rationale is a rationale for why the portion of the budget that has been identified as high risk.
	"budget_medium_risk_amount" decimal(15,2) NULL,    -- Budget Medium Risk Amount is the portion of the budget that has been identified as medium risk.
	"budget_medium_risk_rationale" varchar(4000)	 NULL,    -- Budget Medium Risk Rationale is a rationale for why the portion of the budget that has been identified as medium risk.
	"budget_low_risk_amount" decimal(15,2) NULL,    -- Budget Low Risk Amount is the portion of the budget that has been identified as low risk.
	"budget_low_risk_rationale" varchar(4000)	 NULL,    -- Budget Low Risk Rationale is a rationale for why the portion of the budget that has been identified as low risk.
	"budget_completed_amount" decimal(15,2) NOT NULL,    -- Budget Completed Amount is the portion of the budget that has been expended to complete activities and where it was expended.
	"budget_completed_description" varchar(4000)	 NULL,    -- Budget Completed Description is a description of what portion of the budget was spent and where.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."audit_table_sequence"
	IS 'Added by transform - intent is make this sequence noncached so order is maintained'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."audit_action_code"
	IS 'Contains the reason the audit record is written - Insert/Update/Delete/Conversion'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."project_plan_fiscal_perf_guid"
	IS 'project_plan_fiscal_perf_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."project_plan_fiscal_guid"
	IS 'project_plan_fiscal_guid: Is a foreign key to project_plan_fiscal: Project Plan Fiscal is used to store a plan for the work to be done in a fiscal year for the project. '
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."submitted_timestamp"
	IS 'Submitted Timestamp is the date and time the performance update was entered.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."progress_status_code"
	IS 'progress_status_code: Is a foreign key to progress_status_code: Progress Status Code tracks the progress for a fiscal project. Values are:  	- On Track 	- Deferred 	- Delayed 	- Cancelled'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."plan_fiscal_status_code"
	IS 'plan_fiscal_status_code: Is a foreign key to plan_fiscal_status_code: Plan Fiscal Status Code is the set of statuses a project plan may transition through. Values are:  	- Draft 	- Proposed 	- Prepared 	- In Progress 	- Complete 	- Abandoned'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."reporting_period_code"
	IS 'reporting_period_code: Is a foreign key to reporting_period_code: Reporting Period Code is a list of reporting periods that performance updates can be provided for. Values:  	- Q1 - End of First Quarter 	- Q2 - End of Second Quarter 	- Q3 - End of Third Quarter 	- MARCH7 - March 7 	- CUSTOM - Other'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."submitted_by_name"
	IS 'Submitted By Name is the display name of the person who entered the performance update.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."submitted_by_userid"
	IS 'Submitted By Userid is the IDIR or BCEID userid of the user that created the performance update.   The client has a business requirement to display the Userid of the user in their application interfaces.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."submitted_by_guid"
	IS 'Submitted By Guid is the user GUID identifying the person who created the performance update.   The user guid is stored in this field corresponds to a user authorized in the WebADE platform.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."previous_forecast_amount"
	IS 'Previous Forecast Amount is the amount that was previously forecast. It is set to the Project Plan Fiscal forecast amount if the forecast amount is greater than zero, otherwise it is set to the Project Plan Fiscal Total Cost Estimate Amount. '
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."forecast_amount"
	IS 'Forecast Amount is the total amount the project lead reports will be spent (encumberances and actuals) for the period.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."forecast_adjustment_amount"
	IS 'Forecast Adjustment Amount is difference between the previous forecast amount and the current forecast amount'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."forecast_adjustment_rationale"
	IS 'Forecast Adjustment Rationale is a rationale provided to justify the adjusted forecast.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."general_update_comment"
	IS 'General Update Comment is free-form text providing additional detail regarding the successes, challenges, and progress made.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."budget_high_risk_amount"
	IS 'Budget High Risk Amount is the portion of the budget that has been identified as high risk.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."budget_high_risk_rationale"
	IS 'Budget High Risk Rationale is a rationale for why the portion of the budget that has been identified as high risk.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."budget_medium_risk_amount"
	IS 'Budget Medium Risk Amount is the portion of the budget that has been identified as medium risk.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."budget_medium_risk_rationale"
	IS 'Budget Medium Risk Rationale is a rationale for why the portion of the budget that has been identified as medium risk.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."budget_low_risk_amount"
	IS 'Budget Low Risk Amount is the portion of the budget that has been identified as low risk.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."budget_low_risk_rationale"
	IS 'Budget Low Risk Rationale is a rationale for why the portion of the budget that has been identified as low risk.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."budget_completed_amount"
	IS 'Budget Completed Amount is the portion of the budget that has been expended to complete activities and where it was expended.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."budget_completed_description"
	IS 'Budget Completed Description is a description of what portion of the budget was spent and where.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_perf_audit"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."project_plan_fiscal_perf_audit" ADD CONSTRAINT "ppfyprf_aud_pk"
	PRIMARY KEY (audit_table_sequence)
;


