/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 14-Nov-2024 10:35:59 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."project_audit"
(
	"audit_table_sequence" decimal(15) NOT NULL,    -- Added by transform - intent is make this sequence noncached so order is maintained
	"audit_action_code" varchar(10)	 NOT NULL,    -- Contains the reason the audit record is written - Insert/Update/Delete/Conversion
	"project_guid"  UUID NULL,    -- project_guid is a unique identifier for the record.
	"project_type_code" varchar(10)	 NOT NULL,    -- project_type_code: Is a foreign key to project_type_code: Project Type Code defines the type of the project.  Values are:   	- Fuel Management  	- Cultural & Prescribed Fire
	"project_number" decimal(10) NOT NULL,    -- Project Number is a unique number used to identify a project which can be referenced as a display value in business documents. 
	"site_unit_name" varchar(250)	 NOT NULL,    -- Site Unit Name is the name of the site or unit where the project is located. It is used to build the project identifier.
	"forest_area_code" varchar(10)	 NULL,    -- forest_area_code: Is a foreign key to forest_area_code: Forest Area Code is a list of Ministry Forest Areas Values are:   	- Coast 	- North 	- West
	"general_scope_code" varchar(10)	 NULL,    -- general_scope_code: Is a foreign key to general_scope_code: General Scope Code is the set of high level scopes a project may have. Values are:  	- Landscape Level Activities   	- Site Level Activities 	- Non-Spatial Activities
	"program_area_guid" UUID NOT NULL,    -- program_area_guid: Is a foreign key to program_area: Program Area identifies the agencies that collaborate with MOF on wildfire risk reduction projects funded through CLWRR   Values are:  	- Ministry of Forests 	- Regional Operations 	- BC Wildfire Service 	- BC Parks 	- Ministry of Water, Land and Resource Stewardship WLRS 	- Mountain Resorts Branch (MRB)   Need to verify if Regional Operations is the same as Natural Resource Regions and Districts.
	"forest_region_org_unit_id" decimal(10) NOT NULL,    -- Forest Region Org Unit Identifier is the org unit identifier for the a forest region.
	"forest_district_org_unit_id" decimal(10) NULL,    -- Forest District Org Unit Identifier is the org unit identifier for the a forest district.
	"fire_centre_org_unit_id" decimal(10) NULL,    -- Fire Centre Org Unit Identifier is the org unit identifier for a fire centre in the BCWS Org hieararchy.
	"bc_parks_region_org_unit_id" decimal(10) NULL,    -- BC Parks Region Org Unit Identifier is the org unit identifier for a BC Parks region.
	"bc_parks_section_org_unit_id" decimal(10) NULL,    -- BC Parks Section Org Unit Identifier is the org unit identifier for a BC Parks section.
	"project_name" varchar(300)	 NOT NULL,    -- Project Name is a short name for the proposed project. 
	"project_lead" varchar(300)	 NULL,    -- Project Lead is the full name of the person leading the project.
	"project_description" varchar(4000)	 NULL,    -- Project Description is a description of the project and it's intended purpose. 
	"closest_community_name" varchar(250)	 NULL,    -- Closest Community Name is the name of the community that is closest to the project.
	"total_funding_request_amount" decimal(15,2) NULL,    -- Total Funding Request Amount is the dollar amount requested to fund the completion of the proposed project activities for all fiscal years.
	"total_allocated_amount" decimal(15,2) NULL,    -- Total Allocated Amount is the total budget that has been allocated to the project across all fiscal years.
	"total_planned_project_size_ha" decimal(15,4) NULL DEFAULT 0,    -- Total Planned Project Size Ha is the total land size in hectares that are planned to be treated by the project. This will include land that is planned to be treated in the future.
	"total_planned_cost_per_hectare" decimal(15,2) NULL DEFAULT 0,    -- Total Planned Cost Per Hectare Amount is the planned cost per hectare for the project for all fiscal years. It is calculated as NVL(Total Allocated Amount, Total Funding Request Amount) divided by Total Planned Project Size HA.
	"total_actual_amount" decimal(15,2) NOT NULL DEFAULT 0,    -- Total Actual Amount is the total amount actually spent on the project
	"total_project_size_ha" decimal(15,4) NULL DEFAULT 0,    -- Total Project Size Ha is the total land size in hectares that have been treated by the project. This will be a sum of all the land treated to date.
	"total_cost_per_hectare_amount" decimal(15,2) NULL DEFAULT 0,    -- Total Cost Per Hectare Amount is the cost per hectare for the project for all fiscal years. It is calculated as Total Actual Amount divided by Total Project Size Ha.
	"is_multi_fiscal_year_proj_ind" boolean NOT NULL DEFAULT 'N',    -- Is Multi Fiscal Year Project Ind indicates whether the project spans multiple fiscal years (Y) or not (N).
	"latitude" decimal(9,6) NULL,    -- Latitude is used as part of a latitude/longitude coordinate to locate a project on a map.
	"longitude" decimal(9,6) NULL,    -- Longitude is used as part of a latitude/longitude coordinate to locate a project on a map.
	"last_progress_update_timestamp" TIMESTAMP NULL,    -- Last Progress Update Timestamp records when the last project progress update was reported for the project by the project lead.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "wfprev"."project_audit"."audit_table_sequence"
	IS 'Added by transform - intent is make this sequence noncached so order is maintained'
;

COMMENT ON COLUMN "wfprev"."project_audit"."audit_action_code"
	IS 'Contains the reason the audit record is written - Insert/Update/Delete/Conversion'
;

COMMENT ON COLUMN "wfprev"."project_audit"."project_guid"
	IS 'project_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."project_type_code"
	IS 'project_type_code: Is a foreign key to project_type_code: Project Type Code defines the type of the project.  Values are:   	- Fuel Management  	- Cultural & Prescribed Fire'
;

COMMENT ON COLUMN "wfprev"."project_audit"."project_number"
	IS 'Project Number is a unique number used to identify a project which can be referenced as a display value in business documents. '
;

COMMENT ON COLUMN "wfprev"."project_audit"."site_unit_name"
	IS 'Site Unit Name is the name of the site or unit where the project is located. It is used to build the project identifier.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."forest_area_code"
	IS 'forest_area_code: Is a foreign key to forest_area_code: Forest Area Code is a list of Ministry Forest Areas Values are:   	- Coast 	- North 	- West'
;

COMMENT ON COLUMN "wfprev"."project_audit"."general_scope_code"
	IS 'general_scope_code: Is a foreign key to general_scope_code: General Scope Code is the set of high level scopes a project may have. Values are:  	- Landscape Level Activities   	- Site Level Activities 	- Non-Spatial Activities'
;

COMMENT ON COLUMN "wfprev"."project_audit"."program_area_guid"
	IS 'program_area_guid: Is a foreign key to program_area: Program Area identifies the agencies that collaborate with MOF on wildfire risk reduction projects funded through CLWRR   Values are:  	- Ministry of Forests 	- Regional Operations 	- BC Wildfire Service 	- BC Parks 	- Ministry of Water, Land and Resource Stewardship WLRS 	- Mountain Resorts Branch (MRB)   Need to verify if Regional Operations is the same as Natural Resource Regions and Districts.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."forest_region_org_unit_id"
	IS 'Forest Region Org Unit Identifier is the org unit identifier for the a forest region.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."forest_district_org_unit_id"
	IS 'Forest District Org Unit Identifier is the org unit identifier for the a forest district.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."fire_centre_org_unit_id"
	IS 'Fire Centre Org Unit Identifier is the org unit identifier for a fire centre in the BCWS Org hieararchy.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."bc_parks_region_org_unit_id"
	IS 'BC Parks Region Org Unit Identifier is the org unit identifier for a BC Parks region.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."bc_parks_section_org_unit_id"
	IS 'BC Parks Section Org Unit Identifier is the org unit identifier for a BC Parks section.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."project_name"
	IS 'Project Name is a short name for the proposed project. '
;

COMMENT ON COLUMN "wfprev"."project_audit"."project_lead"
	IS 'Project Lead is the full name of the person leading the project.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."project_description"
	IS 'Project Description is a description of the project and it''s intended purpose. '
;

COMMENT ON COLUMN "wfprev"."project_audit"."closest_community_name"
	IS 'Closest Community Name is the name of the community that is closest to the project.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."total_funding_request_amount"
	IS 'Total Funding Request Amount is the dollar amount requested to fund the completion of the proposed project activities for all fiscal years.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."total_allocated_amount"
	IS 'Total Allocated Amount is the total budget that has been allocated to the project across all fiscal years.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."total_planned_project_size_ha"
	IS 'Total Planned Project Size Ha is the total land size in hectares that are planned to be treated by the project. This will include land that is planned to be treated in the future.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."total_planned_cost_per_hectare"
	IS 'Total Planned Cost Per Hectare Amount is the planned cost per hectare for the project for all fiscal years. It is calculated as NVL(Total Allocated Amount, Total Funding Request Amount) divided by Total Planned Project Size HA.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."total_actual_amount"
	IS 'Total Actual Amount is the total amount actually spent on the project'
;

COMMENT ON COLUMN "wfprev"."project_audit"."total_project_size_ha"
	IS 'Total Project Size Ha is the total land size in hectares that have been treated by the project. This will be a sum of all the land treated to date.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."total_cost_per_hectare_amount"
	IS 'Total Cost Per Hectare Amount is the cost per hectare for the project for all fiscal years. It is calculated as Total Actual Amount divided by Total Project Size Ha.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."is_multi_fiscal_year_proj_ind"
	IS 'Is Multi Fiscal Year Project Ind indicates whether the project spans multiple fiscal years (Y) or not (N).'
;

COMMENT ON COLUMN "wfprev"."project_audit"."latitude"
	IS 'Latitude is used as part of a latitude/longitude coordinate to locate a project on a map.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."longitude"
	IS 'Longitude is used as part of a latitude/longitude coordinate to locate a project on a map.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."last_progress_update_timestamp"
	IS 'Last Progress Update Timestamp records when the last project progress update was reported for the project by the project lead.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."project_audit"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."project_audit" ADD CONSTRAINT "prjct_aud_pk"
	PRIMARY KEY ()
;