/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 12-Nov-2024 4:33:43 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."program_area"
(
	"program_area_guid" UUID NOT NULL,    -- program_area_guid is a unique identifier for the record.
	"program_area_name" varchar(100)	 NOT NULL,    -- Program Area Name is the name of the program area.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."program_area"
	IS 'Program Area identifies the agencies that collaborate with MOF on wildfire risk reduction projects funded through CLWRR   Values are:  	- Ministry of Forests 	- Regional Operations 	- BC Wildfire Service 	- BC Parks 	- Ministry of Water, Land and Resource Stewardship WLRS 	- Mountain Resorts Branch (MRB)   Need to verify if Regional Operations is the same as Natural Resource Regions and Districts.'
;

COMMENT ON COLUMN "wfprev"."program_area"."program_area_guid"
	IS 'program_area_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."program_area"."program_area_name"
	IS 'Program Area Name is the name of the program area.'
;

COMMENT ON COLUMN "wfprev"."program_area"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."program_area"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."program_area"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."program_area"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."program_area"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."program_area" ADD CONSTRAINT "prgar_pk"
	PRIMARY KEY ("program_area_guid")
;

ALTER TABLE "wfprev"."program_area" ADD CONSTRAINT "prgar_uk" UNIQUE ("program_area_name")
;