export const SCOPE_APPLICATION_PREFIX = 'WFPREV.';

export const ROLES_UI = {
  ADMIN: `${SCOPE_APPLICATION_PREFIX}WFPREV_ADMIN`,
  EDITOR: `${SCOPE_APPLICATION_PREFIX}WFPREV_EDITOR`,
  READ_ONLY: `${SCOPE_APPLICATION_PREFIX}WFPREV_READ-ONLY`, 
};
