/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 13-Jan-2025 4:04:04 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."activity_progress_audit"
(
	"audit_table_sequence" decimal(15) NOT NULL,    -- Added by transform - intent is make this sequence noncached so order is maintained
	"audit_action_code" varchar(10)	 NOT NULL,    -- Contains the reason the audit record is written - Insert/Update/Delete/Conversion
	"activity_progress_guid" UUID NULL,    -- activity_progress_guid is a unique identifier for the record.
	"activity_guid" UUID NOT NULL,    -- activity_guid: Is a foreign key to activity: Activity is used to track the treatment activities that are planned for the project for the fiscal year.
	"project_plan_fiscal_perf_guid" UUID NOT NULL,    -- project_plan_fiscal_perf_guid: Is a foreign key to project_plan_fiscal_perf: Project Plan Fiscal Performance records the progress made to date on a project for the fiscal year as reported by the business area.  
	"entered_timestamp" TIMESTAMP NOT NULL,    -- Entered Timestamp is the date and time the comment was entered.
	"activity_status_code" varchar(10)	 NOT NULL,    -- activity_status_code: Is a foreign key to activity_status_code: Activity Status Code is the status of an activity for a fiscal year. Values are:  	- Active 	- Completed 	- Deleted 	- Archived
	"contract_phase_code" varchar(10)	 NULL,    -- contract_phase_code: Is a foreign key to contract_phase_code: Contract Phase Code is used to track the general status of contracts that are out for bid to suppliers to complete treatment work for the project. Values are:  	- Contract Out For Bid 	- Contract Awarded 	- Multiple Contracts Out For Bid 	- Multiple Contracts Awarded
	"risk_rating_code" varchar(10)	 NOT NULL,    -- risk_rating_code: Is a foreign key to risk_rating_code: Risk Rating Code are ratings that determine the level of risk of a project not spending allocated budget.  Values:  	- Low Risk 	- Moderate Risk 	- High Risk
	"planned_spend_amount" decimal(15,2) NULL,
	"reported_spend_amount" decimal(15,2) NULL,    -- Reported Spend Amount is the amount that has been reported to have been spent on the activity. It may include amounts that have not been entered in CFS yet.
	"completed_area_ha" decimal(15,4) NULL,    -- Completed Area Ha is the area that a treatment has been completed by the applied activity.
	"progress_comment" varchar(4000)	 NULL,    -- Progress Comment is free-form text providing additional detail regarding the progress made on a project or activity.
	"commenter_userid" varchar(64)	 NULL,    -- Commenter Userid is the IDIR or BCEID userid of the user that added the comment.   The client has a business requirement to display the Userid of the user in their application interfaces.
	"commenter_guid" varchar(36)	 NULL,    -- Commenter Guid is the user GUID identifying the person who created the comment.   The user guid is stored in this field corresponds to a user authorized in the WebADE platform.
	"system_generated_ind" boolean NOT NULL DEFAULT 'N',    -- System Generated Ind indicates whether or not the comment was generated by the application ('Y') or was user entered ('N').
	"outstanding_obligations_ind" boolean NOT NULL DEFAULT 'N',    -- Outstanding Obligations Ind indicates whether there are outstanding obligations for the treatment activity (Y) or not (N). As activities draw to an end, there may be some uncompleted work for which there is an obligation to complete at another time. This field indicates if there are such obligations.
	"activity_comment" varchar(4000)	 NULL,    -- Treatment Activity Comment is used to document activity comments including outstanding obligations.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."audit_table_sequence"
	IS 'Added by transform - intent is make this sequence noncached so order is maintained'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."audit_action_code"
	IS 'Contains the reason the audit record is written - Insert/Update/Delete/Conversion'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."activity_progress_guid"
	IS 'activity_progress_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."activity_guid"
	IS 'activity_guid: Is a foreign key to activity: Activity is used to track the treatment activities that are planned for the project for the fiscal year.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."project_plan_fiscal_perf_guid"
	IS 'project_plan_fiscal_perf_guid: Is a foreign key to project_plan_fiscal_perf: Project Plan Fiscal Performance records the progress made to date on a project for the fiscal year as reported by the business area.  '
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."entered_timestamp"
	IS 'Entered Timestamp is the date and time the comment was entered.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."activity_status_code"
	IS 'activity_status_code: Is a foreign key to activity_status_code: Activity Status Code is the status of an activity for a fiscal year. Values are:  	- Active 	- Completed 	- Deleted 	- Archived'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."contract_phase_code"
	IS 'contract_phase_code: Is a foreign key to contract_phase_code: Contract Phase Code is used to track the general status of contracts that are out for bid to suppliers to complete treatment work for the project. Values are:  	- Contract Out For Bid 	- Contract Awarded 	- Multiple Contracts Out For Bid 	- Multiple Contracts Awarded'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."risk_rating_code"
	IS 'risk_rating_code: Is a foreign key to risk_rating_code: Risk Rating Code are ratings that determine the level of risk of a project not spending allocated budget.  Values:  	- Low Risk 	- Moderate Risk 	- High Risk'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."reported_spend_amount"
	IS 'Reported Spend Amount is the amount that has been reported to have been spent on the activity. It may include amounts that have not been entered in CFS yet.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."completed_area_ha"
	IS 'Completed Area Ha is the area that a treatment has been completed by the applied activity.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."progress_comment"
	IS 'Progress Comment is free-form text providing additional detail regarding the progress made on a project or activity.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."commenter_userid"
	IS 'Commenter Userid is the IDIR or BCEID userid of the user that added the comment.   The client has a business requirement to display the Userid of the user in their application interfaces.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."commenter_guid"
	IS 'Commenter Guid is the user GUID identifying the person who created the comment.   The user guid is stored in this field corresponds to a user authorized in the WebADE platform.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."system_generated_ind"
	IS 'System Generated Ind indicates whether or not the comment was generated by the application (''Y'') or was user entered (''N'').'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."outstanding_obligations_ind"
	IS 'Outstanding Obligations Ind indicates whether there are outstanding obligations for the treatment activity (Y) or not (N). As activities draw to an end, there may be some uncompleted work for which there is an obligation to complete at another time. This field indicates if there are such obligations.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."activity_comment"
	IS 'Treatment Activity Comment is used to document activity comments including outstanding obligations.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."activity_progress_audit"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."activity_progress_audit" ADD CONSTRAINT "actprg_aud_pk"
	PRIMARY KEY (audit_table_sequence)
;