CREATE OR REPLACE FUNCTION wfprev.fnc_audit_project_plan_fiscal() RETURNS TRIGGER AS $$
DECLARE 
  v_audit_action VARCHAR(10); 
BEGIN 
  v_audit_action := TG_OP; 
  IF ((TG_OP = 'INSERT') OR (TG_OP = 'UPDATE')) THEN 
    INSERT INTO wfprev.project_plan_fiscal_audit( 
      audit_table_sequence, 
      audit_action_code, 
      project_plan_fiscal_guid,
      project_guid,
      activity_category_code,
      fiscal_year,
      ancillary_funding_source_guid,
      project_plan_status_code,
      plan_fiscal_status_code,
      endorsement_code,
      project_fiscal_name,
      project_fiscal_description,
      business_area_comment,
      estimated_clwrr_alloc_amount,
      total_cost_estimate_amount,
      cfs_project_code,
      fiscal_ancillary_fund_amount,
      fiscal_planned_project_size_ha,
      fiscal_planned_cost_per_ha_amt,
      fiscal_reported_spend_amount,
      fiscal_actual_amount,
      fiscal_completed_size_ha,
      fiscal_actual_cost_per_ha_amt,
      first_nations_deliv_part_ind,
      first_nations_engagement_ind,
      first_nations_partner,
      other_partner,
      results_number,
      results_opening_id,
      results_contact_email,
      submitted_by_name,
      submitted_by_user_guid,
      submitted_by_user_userid,
      submission_timestamp,
      endorsement_eval_timestamp,
      endorser_name,
      endorser_user_guid,
      endorser_user_userid,
      endorsement_timestamp,
      endorsement_comment,
      is_approved_ind,
      approver_name,
      approver_user_guid,
      approver_user_userid,
      approved_timestamp,
      accomplishments_comment,
      is_delayed_ind,
      delay_rationale,
      abandoned_rationale,
      last_progress_update_timestamp,
      revision_count,
      create_user,
      create_date,
      update_user,
      update_date,
      fiscal_forecast_amount,
      proposal_type_code 
    ) 
    VALUES ( 
      nextval('wfprev.prev_audit_table_seq'),
      v_audit_action, 
      NEW.project_plan_fiscal_guid,
      NEW.project_guid,
      NEW.activity_category_code,
      NEW.fiscal_year,
      NEW.ancillary_funding_source_guid,
      NEW.project_plan_status_code,
      NEW.plan_fiscal_status_code,
      NEW.endorsement_code,
      NEW.project_fiscal_name,
      NEW.project_fiscal_description,
      NEW.business_area_comment,
      NEW.estimated_clwrr_alloc_amount,
      NEW.total_cost_estimate_amount,
      NEW.cfs_project_code,
      NEW.fiscal_ancillary_fund_amount,
      NEW.fiscal_planned_project_size_ha,
      NEW.fiscal_planned_cost_per_ha_amt,
      NEW.fiscal_reported_spend_amount,
      NEW.fiscal_actual_amount,
      NEW.fiscal_completed_size_ha,
      NEW.fiscal_actual_cost_per_ha_amt,
      NEW.first_nations_deliv_part_ind,
      NEW.first_nations_engagement_ind,
      NEW.first_nations_partner,
      NEW.other_partner,
      NEW.results_number,
      NEW.results_opening_id,
      NEW.results_contact_email,
      NEW.submitted_by_name,
      NEW.submitted_by_user_guid,
      NEW.submitted_by_user_userid,
      NEW.submission_timestamp,
      NEW.endorsement_eval_timestamp,
      NEW.endorser_name,
      NEW.endorser_user_guid,
      NEW.endorser_user_userid,
      NEW.endorsement_timestamp,
      NEW.endorsement_comment,
      NEW.is_approved_ind,
      NEW.approver_name,
      NEW.approver_user_guid,
      NEW.approver_user_userid,
      NEW.approved_timestamp,
      NEW.accomplishments_comment,
      NEW.is_delayed_ind,
      NEW.delay_rationale,
      NEW.abandoned_rationale,
      NEW.last_progress_update_timestamp,
      NEW.revision_count,
      NEW.create_user,
      NEW.create_date,
      NEW.update_user,
      NEW.update_date,
      NEW.fiscal_forecast_amount,
      NEW.proposal_type_code 
    ); 
    RETURN NEW; 

  ELSIF (TG_OP = 'DELETE') THEN 
    INSERT INTO wfprev.project_plan_fiscal_audit( 
      audit_table_sequence, 
      audit_action_code, 
      project_plan_fiscal_guid,
      project_guid,
      activity_category_code,
      fiscal_year,
      ancillary_funding_source_guid,
      project_plan_status_code,
      plan_fiscal_status_code,
      endorsement_code,
      project_fiscal_name,
      project_fiscal_description,
      business_area_comment,
      estimated_clwrr_alloc_amount,
      total_cost_estimate_amount,
      cfs_project_code,
      fiscal_ancillary_fund_amount,
      fiscal_planned_project_size_ha,
      fiscal_planned_cost_per_ha_amt,
      fiscal_reported_spend_amount,
      fiscal_actual_amount,
      fiscal_completed_size_ha,
      fiscal_actual_cost_per_ha_amt,
      first_nations_deliv_part_ind,
      first_nations_engagement_ind,
      first_nations_partner,
      other_partner,
      results_number,
      results_opening_id,
      results_contact_email,
      submitted_by_name,
      submitted_by_user_guid,
      submitted_by_user_userid,
      submission_timestamp,
      endorsement_eval_timestamp,
      endorser_name,
      endorser_user_guid,
      endorser_user_userid,
      endorsement_timestamp,
      endorsement_comment,
      is_approved_ind,
      approver_name,
      approver_user_guid,
      approver_user_userid,
      approved_timestamp,
      accomplishments_comment,
      is_delayed_ind,
      delay_rationale,
      abandoned_rationale,
      last_progress_update_timestamp,
      revision_count,
      create_user,
      create_date,
      update_user,
      update_date,
      fiscal_forecast_amount,
      proposal_type_code 
    ) 
    VALUES ( 
      nextval('wfprev.prev_audit_table_seq'),
      v_audit_action, 
      OLD.project_plan_fiscal_guid,
      OLD.project_guid,
      OLD.activity_category_code,
      OLD.fiscal_year,
      OLD.ancillary_funding_source_guid,
      OLD.project_plan_status_code,
      OLD.plan_fiscal_status_code,
      OLD.endorsement_code,
      OLD.project_fiscal_name,
      OLD.project_fiscal_description,
      OLD.business_area_comment,
      OLD.estimated_clwrr_alloc_amount,
      OLD.total_cost_estimate_amount,
      OLD.cfs_project_code,
      OLD.fiscal_ancillary_fund_amount,
      OLD.fiscal_planned_project_size_ha,
      OLD.fiscal_planned_cost_per_ha_amt,
      OLD.fiscal_reported_spend_amount,
      OLD.fiscal_actual_amount,
      OLD.fiscal_completed_size_ha,
      OLD.fiscal_actual_cost_per_ha_amt,
      OLD.first_nations_deliv_part_ind,
      OLD.first_nations_engagement_ind,
      OLD.first_nations_partner,
      OLD.other_partner,
      OLD.results_number,
      OLD.results_opening_id,
      OLD.results_contact_email,
      OLD.submitted_by_name,
      OLD.submitted_by_user_guid,
      OLD.submitted_by_user_userid,
      OLD.submission_timestamp,
      OLD.endorsement_eval_timestamp,
      OLD.endorser_name,
      OLD.endorser_user_guid,
      OLD.endorser_user_userid,
      OLD.endorsement_timestamp,
      OLD.endorsement_comment,
      OLD.is_approved_ind,
      OLD.approver_name,
      OLD.approver_user_guid,
      OLD.approver_user_userid,
      OLD.approved_timestamp,
      OLD.accomplishments_comment,
      OLD.is_delayed_ind,
      OLD.delay_rationale,
      OLD.abandoned_rationale,
      OLD.last_progress_update_timestamp,
      OLD.revision_count,
      OLD.create_user,
      OLD.create_date,
      OLD.update_user,
      OLD.update_date,
      OLD.fiscal_forecast_amount,
      OLD.proposal_type_code 
    ); 
    RETURN OLD; 

  ELSE 
    RAISE WARNING '[wfprev.fnc_audit_project_plan_fiscal] - Other action occurred: %, at %',TG_OP,now(); 
    RETURN NULL; 
  END IF; 

EXCEPTION 
  WHEN data_exception THEN 
      RAISE WARNING '[wfprev.fnc_audit_project_plan_fiscal] - UDF ERROR [DATA EXCEPTION] - SQLSTATE: %, SQLERRM: %',SQLSTATE,SQLERRM; 
      RETURN NULL; 
  WHEN unique_violation THEN 
      RAISE WARNING '[wfprev.fnc_audit_project_plan_fiscal] - UDF ERROR [UNIQUE] - SQLSTATE: %, SQLERRM: %',SQLSTATE,SQLERRM; 
      RETURN NULL; 
  WHEN others THEN 
      RAISE WARNING '[wfprev.fnc_audit_project_plan_fiscal] - UDF ERROR [OTHER] - SQLSTATE: %, SQLERRM: %',SQLSTATE,SQLERRM; 
      RETURN NULL; 
END; 
$$ LANGUAGE plpgsql; 

CREATE OR REPLACE TRIGGER trigger_audit_project_plan_fiscal_perf
AFTER INSERT OR UPDATE OR DELETE ON wfprev.project_plan_fiscal_perf 
FOR EACH ROW EXECUTE PROCEDURE wfprev.fnc_audit_project_plan_fiscal_perf();