package ca.bc.gov.nrs.wfprev.data.repositories;

import java.util.UUID;

import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import ca.bc.gov.nrs.wfprev.common.repository.CommonRepository;
import ca.bc.gov.nrs.wfprev.data.model.ExampleEntity;

/**
 * Example repository rest resource
 * If you use "Exported = false", it will disable the autogenerated "endpoints" that 
 * are accessible in a resful way, and you can use this Repository in a Controller
 * This is the standard pattern we'd prefer
 * 
 * if you set a path, and exported = true (the default), all of the standard JPA functions
 * and any custom ones you define here, will be exposed as endpoints. This can have some
 * advantages, but it also leads to some confusion on where endpoints are defined so its
 * generally easier to understand it via a Controller
 * 
 * Search/query methods added here will be accessible wherever you use the repository, so this
 * is a great place to put standard jpaQueries (like the one that exists on CommonRepository already)
 * 
 * Note, if you want to use myBatis instead, you won't need this stuff. 
 */

//@RepositoryRestResource(collectionResourceRel="example", path="example")
@RepositoryRestResource(exported = false)
public interface ExampleRepository extends CommonRepository<ExampleEntity, String> {
  
}