/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 14-Feb-2025 3:28:58 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."funding_stream"
(
	"funding_stream_guid" UUID NOT NULL,    -- funding_stream_guid is a unique identifier for the record.
	"funding_stream" varchar(100)	 NOT NULL,    -- Funding Stream is the name of the funding stream providing monies.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."funding_stream"
	IS 'Funding Stream defines the funding streams that provides monies to fund projects. Values are:  	- Fuels Management 	- Cultural and Prescribed Burn.   Note: The funding streams currently align 1 to 1 with project type, but this can change in the future to a larger set of funding streams.'
;

COMMENT ON COLUMN "wfprev"."funding_stream"."funding_stream_guid"
	IS 'funding_stream_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."funding_stream"."funding_stream"
	IS 'Funding Stream is the name of the funding stream providing monies.'
;

COMMENT ON COLUMN "wfprev"."funding_stream"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."funding_stream"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."funding_stream"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."funding_stream"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."funding_stream"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."funding_stream" ADD CONSTRAINT "fndstrm_pk"
	PRIMARY KEY ("funding_stream_guid")
;

ALTER TABLE "wfprev"."funding_stream" ADD CONSTRAINT "fndstrm_uk" UNIQUE ("funding_stream")
;