GRANT SELECT  ON ALL SEQUENCES IN SCHEMA wfprev TO proxy_wf1_prev_rest;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA wfprev TO proxy_wf1_prev_rest;
ALTER DEFAULT PRIVILEGES IN SCHEMA wfprev GRANT SELECT, INSERT, UPDATE, DELETE ON tables TO proxy_wf1_prev_rest;
ALTER DEFAULT PRIVILEGES IN SCHEMA wfprev GRANT SELECT  ON SEQUENCES TO proxy_wf1_prev_rest;
ALTER ROLE proxy_wf1_prev_rest SET search_path TO wfprev;