

ALTER TABLE wfprev.project ADD COLUMN "results_project_code" varchar(25)   NULL;

COMMENT ON COLUMN "wfprev"."project"."results_project_code"
  IS 'RESULTS Project Code is a unique code that is generated by BCWS to identify the project, that will be stored in the RESULTS system. The project code can be considered to be a type of project number which identifies the project. Example RESULTS Project Code: WRSE0180'
;

ALTER TABLE wfprev.project_audit ADD COLUMN "results_project_code" varchar(25)   NULL;

COMMENT ON COLUMN "wfprev"."project_audit"."results_project_code"
  IS 'RESULTS Project Code is a unique code that is generated by BCWS to identify the project, that will be stored in the RESULTS system. The project code can be considered to be a type of project number which identifies the project. Example RESULTS Project Code: WRSE0180'
;

