/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 21-Jan-2025 4:22:11 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."fuel_management_plan"
(
	"fuel_management_plan_guid" UUID NOT NULL,    -- fuel_management_plan_guid is a unique identifier for the record.
	"project_plan_fiscal_guid" UUID NOT NULL,    -- project_plan_fiscal_guid: Is a foreign key to project_plan_fiscal: Project Plan Fiscal is used to store a plan for the work to be done in a fiscal year for the project. 
	"tactical_plans_outside_wui" varchar(4000)	 NULL,    -- Tactical Plans Outside Wildland Urban Interface are tactical plans with an area of interest that expands outside of the wildland urban interface.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."fuel_management_plan"
	IS 'Fuel Management Plan is a subclass of a Project Fiscal Plan and contains attributes specific to Fuel Management Project Plans'
;

COMMENT ON COLUMN "wfprev"."fuel_management_plan"."fuel_management_plan_guid"
	IS 'fuel_management_plan_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_plan"."project_plan_fiscal_guid"
	IS 'project_plan_fiscal_guid: Is a foreign key to project_plan_fiscal: Project Plan Fiscal is used to store a plan for the work to be done in a fiscal year for the project. '
;

COMMENT ON COLUMN "wfprev"."fuel_management_plan"."tactical_plans_outside_wui"
	IS 'Tactical Plans Outside Wildland Urban Interface are tactical plans with an area of interest that expands outside of the wildland urban interface.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_plan"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_plan"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_plan"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_plan"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_plan"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."fuel_management_plan" ADD CONSTRAINT "fmpln_pk"
	PRIMARY KEY ("fuel_management_plan_guid")
;

ALTER TABLE "wfprev"."fuel_management_plan" ADD CONSTRAINT "fmpln_uk" UNIQUE ("project_plan_fiscal_guid")
;

CREATE INDEX "fmpln_prjpfy_idx" ON "wfprev"."fuel_management_plan" ("project_plan_fiscal_guid" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfprev"."fuel_management_plan" ADD CONSTRAINT "fmpln_prjpfy_fk"
	FOREIGN KEY ("project_plan_fiscal_guid") REFERENCES "wfprev"."project_plan_fiscal" ("project_plan_fiscal_guid") ON DELETE No Action ON UPDATE No Action
;