GRANT USAGE ON SCHEMA wfprev TO app_wf1_prev;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA wfprev TO app_wf1_prev;

ALTER DEFAULT PRIVILEGES IN SCHEMA wfprev
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_wf1_prev;