/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 18-Dec-2024 1:22:52 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."event_history"
(
	"event_history_guid" UUID NOT NULL,    -- event_history_guid is a unique identifier for the record.
	"event_history_type_code" varchar(10)	 NOT NULL,    -- event_history_type_code: Is a foreign key to event_history_type_code: Event History Type Code describes the types of history events that can be created.  Values are:  	- Event 	- Comment
	"source_object_name_code" varchar(30)	 NOT NULL,    -- source_object_name_code: Is a foreign key to source_object_name_code: Source Object Name Code is a table to hold the name of the table that the attachment belongs to. For instance, when a manifest is attached to a Resource Request, the code value in this table will be RSRC_RQST_SUBMISSION. When a Standing Offer is attached to an Agreement, the value in this table will be AGREEMENT.  For this release, there are only two values in this table: * RSRC_RQST_SUBMISSION * AGREEMENT * AIRCRAFT_DETAIL * Resource Unit * Resource Group * Contact * Supplier
	"source_object_unique_id" varchar(50)	 NOT NULL,    -- Source Object Unique Identifier is the actual primary key value of the source object that spawned the event.  This, along with the Source Object Name will fully identify what the event belongs to. 
	"event_timestamp" TIMESTAMP NULL,    -- Last Updated Timestamp is the date and time the Supplier was last updated.
	"event_comment" varchar(4000)	 NOT NULL,    -- Event Comment is either a system generated event comment, or a comment for a manual event added by a staff member.
	"event_created_by_user_type" varchar(3)	 NULL,    -- Event Created By User Type corresponds user types stored in the WebADE User_Type_Code table, which has values BC Services Card, Government, Business Partner, Unverified Individual, Verified, Individual, Service Client.
	"event_created_by_userid" varchar(100)	 NULL,    -- Event Created By Userid is the IDIR or BCEID userid of the ministry staff member that created the event.
	"event_created_by_user_guid" varchar(32)	 NULL,    -- Event Created By User Guid is the user GUID of the ministry staff member that created the event.  The user guid is stored in this field corresponds to a user authorized in the WebADE platform.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."event_history"
	IS 'Event History is used to track significant events that occur for various modules of the system. For example, the  table can track when a create supplier, update supplier, or delete supplier event has occurred.   The staff person can add manual events to the tables as comments.'
;

COMMENT ON COLUMN "wfprev"."event_history"."event_history_guid"
	IS 'event_history_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."event_history"."event_history_type_code"
	IS 'event_history_type_code: Is a foreign key to event_history_type_code: Event History Type Code describes the types of history events that can be created.  Values are:  	- Event 	- Comment'
;

COMMENT ON COLUMN "wfprev"."event_history"."source_object_name_code"
	IS 'source_object_name_code: Is a foreign key to source_object_name_code: Source Object Name Code is a table to hold the name of the table that the attachment belongs to. For instance, when a manifest is attached to a Resource Request, the code value in this table will be RSRC_RQST_SUBMISSION. When a Standing Offer is attached to an Agreement, the value in this table will be AGREEMENT.  For this release, there are only two values in this table: * RSRC_RQST_SUBMISSION * AGREEMENT * AIRCRAFT_DETAIL * Resource Unit * Resource Group * Contact * Supplier'
;

COMMENT ON COLUMN "wfprev"."event_history"."source_object_unique_id"
	IS 'Source Object Unique Identifier is the actual primary key value of the source object that spawned the event.  This, along with the Source Object Name will fully identify what the event belongs to. '
;

COMMENT ON COLUMN "wfprev"."event_history"."event_timestamp"
	IS 'Last Updated Timestamp is the date and time the Supplier was last updated.'
;

COMMENT ON COLUMN "wfprev"."event_history"."event_comment"
	IS 'Event Comment is either a system generated event comment, or a comment for a manual event added by a staff member.'
;

COMMENT ON COLUMN "wfprev"."event_history"."event_created_by_user_type"
	IS 'Event Created By User Type corresponds user types stored in the WebADE User_Type_Code table, which has values BC Services Card, Government, Business Partner, Unverified Individual, Verified, Individual, Service Client.'
;

COMMENT ON COLUMN "wfprev"."event_history"."event_created_by_userid"
	IS 'Event Created By Userid is the IDIR or BCEID userid of the ministry staff member that created the event.'
;

COMMENT ON COLUMN "wfprev"."event_history"."event_created_by_user_guid"
	IS 'Event Created By User Guid is the user GUID of the ministry staff member that created the event.  The user guid is stored in this field corresponds to a user authorized in the WebADE platform.'
;

COMMENT ON COLUMN "wfprev"."event_history"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."event_history"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."event_history"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."event_history"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."event_history"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."event_history" ADD CONSTRAINT "evthist_pk"
	PRIMARY KEY ("event_history_guid")
;

ALTER TABLE "wfprev"."event_history" ADD CONSTRAINT "evthist_uk" UNIQUE ("event_history_type_code","source_object_name_code","source_object_unique_id","event_timestamp")
;

CREATE INDEX "evthist_ehtcd_idx" ON "wfprev"."event_history" ("event_history_type_code" ASC)
;

CREATE INDEX "evthist_sonc_idx" ON "wfprev"."event_history" ("source_object_name_code" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfprev"."event_history" ADD CONSTRAINT "evthist_ehtcd_fk"
	FOREIGN KEY ("event_history_type_code") REFERENCES "wfprev"."event_history_type_code" ("event_history_type_code") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "wfprev"."event_history" ADD CONSTRAINT "evthist_sonc_fk"
	FOREIGN KEY ("source_object_name_code") REFERENCES "wfprev"."source_object_name_code" ("source_object_name_code") ON DELETE No Action ON UPDATE No Action
;