/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 18-Dec-2024 1:22:52 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."file_attachment"
(
	"file_attachment_guid" UUID NOT NULL,    -- file_attachment_guid is a unique identifier for the record.
	"source_object_name_code" varchar(30)	 NOT NULL,    -- source_object_name_code: Is a foreign key to source_object_name_code: Source Object Name Code is a table to hold the name of the table that the attachment belongs to. For instance, when a manifest is attached to a Resource Request, the code value in this table will be RSRC_RQST_SUBMISSION. When a Standing Offer is attached to an Agreement, the value in this table will be AGREEMENT.  For this release, there are only two values in this table: * RSRC_RQST_SUBMISSION * AGREEMENT * AIRCRAFT_DETAIL * Resource Unit * Resource Group * Contact * Supplier
	"source_object_unique_id" varchar(50)	 NOT NULL,    -- Source Object Unique Identifier is the actual primary key value of the source object that owns the attachment. This, along with the Source Object Name will fully identify what the attachment belongs to. With including future source object types, we don't know if the ID of future objects is going to be of type number, string or some other data type. In order to accommodate any date type, this column is of type string.
	"document_path" varchar(2000)	 NOT NULL,    -- Document Path is the full path to where the attachment document is located. Currently, this will be a full URL on a server including the document name and file extension.
	"file_identifier" varchar(256)	 NULL,    -- File Identifier is the Identifier of a file stored in the Document Management System.
	"wildfire_year" decimal(4) NULL,    -- Wildfire Year is the wildfire year the roster is prepared for.
	"attachment_content_type_code" varchar(30)	 NOT NULL,    -- attachment_content_type_code: Is a foreign key to attachment_content_type_code: Attachment Content Type Code holds the type of document based on the content. For instance, if the document is a Map, this will indicate "Map".  The current values are: * Map * Directions * Manifest * Document * Image * Pilot Information Package
	"attachment_description" varchar(150)	 NULL,    -- Attachment Description is a short description of the attachment, or a user friendly name for the attachment. This is to help users understand in a user friendly manner what the attachment is, rather than relying on the document URL.
	"attachment_read_only_ind" boolean NOT NULL DEFAULT 'N',    -- Attachment Read Only Ind indicates whether the wildfire attachment file is read only (Y) or not (N). If it is not read only it can be deleted and overwritten.
	"uploaded_by_user_type" varchar(3)	 NULL,    -- Uploaded By User Type corresponds user types stored in the WebADE User_Type_Code table, which has values BC Services Card, Government, Business Partner, Unverified Individual, Verified, Individual, Service Client.
	"uploaded_by_userid" varchar(100)	 NULL,    -- Uploaded By Userid is the IDIR or BCEID userid of the person that uploaded the attachment.
	"uploaded_by_user_guid" varchar(32)	 NULL,    -- Uploaded By User Guid is the user GUID of the person that uploaded the attachment.  The user guid is stored in this field corresponds to a user authorized in the WebADE platform.
	"uploaded_by_timestamp" TIMESTAMP NULL,    -- Uploaded By Timestamp is the date and time the attachment was uploaded.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."file_attachment"
	IS 'File Attachment is used to track file attachments for the Resource Management System. It was formerly known as the Wildfire Attachment table.   The File Attachment  table allows for attachments to be linked to various business objects in the system by mapping a file attachment to the ID of the Source Object and the Source Object Name Code.  This table will hold a document path, a foreign key to the Source Object Name table and an ID of the Source Object that owns the attachment. This will bring together the document path with the object that owns it and the table where the object is located.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."file_attachment_guid"
	IS 'file_attachment_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."source_object_name_code"
	IS 'source_object_name_code: Is a foreign key to source_object_name_code: Source Object Name Code is a table to hold the name of the table that the attachment belongs to. For instance, when a manifest is attached to a Resource Request, the code value in this table will be RSRC_RQST_SUBMISSION. When a Standing Offer is attached to an Agreement, the value in this table will be AGREEMENT.  For this release, there are only two values in this table: * RSRC_RQST_SUBMISSION * AGREEMENT * AIRCRAFT_DETAIL * Resource Unit * Resource Group * Contact * Supplier'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."source_object_unique_id"
	IS 'Source Object Unique Identifier is the actual primary key value of the source object that owns the attachment. This, along with the Source Object Name will fully identify what the attachment belongs to. With including future source object types, we don''t know if the ID of future objects is going to be of type number, string or some other data type. In order to accommodate any date type, this column is of type string.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."document_path"
	IS 'Document Path is the full path to where the attachment document is located. Currently, this will be a full URL on a server including the document name and file extension.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."file_identifier"
	IS 'File Identifier is the Identifier of a file stored in the Document Management System.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."wildfire_year"
	IS 'Wildfire Year is the wildfire year the roster is prepared for.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."attachment_content_type_code"
	IS 'attachment_content_type_code: Is a foreign key to attachment_content_type_code: Attachment Content Type Code holds the type of document based on the content. For instance, if the document is a Map, this will indicate "Map".  The current values are: * Map * Directions * Manifest * Document * Image * Pilot Information Package'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."attachment_description"
	IS 'Attachment Description is a short description of the attachment, or a user friendly name for the attachment. This is to help users understand in a user friendly manner what the attachment is, rather than relying on the document URL.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."attachment_read_only_ind"
	IS 'Attachment Read Only Ind indicates whether the wildfire attachment file is read only (Y) or not (N). If it is not read only it can be deleted and overwritten.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."uploaded_by_user_type"
	IS 'Uploaded By User Type corresponds user types stored in the WebADE User_Type_Code table, which has values BC Services Card, Government, Business Partner, Unverified Individual, Verified, Individual, Service Client.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."uploaded_by_userid"
	IS 'Uploaded By Userid is the IDIR or BCEID userid of the person that uploaded the attachment.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."uploaded_by_user_guid"
	IS 'Uploaded By User Guid is the user GUID of the person that uploaded the attachment.  The user guid is stored in this field corresponds to a user authorized in the WebADE platform.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."uploaded_by_timestamp"
	IS 'Uploaded By Timestamp is the date and time the attachment was uploaded.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."file_attachment"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."file_attachment" ADD CONSTRAINT "flatt_pk"
	PRIMARY KEY ("file_attachment_guid")
;

ALTER TABLE "wfprev"."file_attachment" ADD CONSTRAINT "flatt_uk" UNIQUE ("source_object_name_code","source_object_unique_id","document_path","file_identifier","wildfire_year")
;

CREATE INDEX "flatt_sonc_idx" ON "wfprev"."file_attachment" ("source_object_name_code" ASC)
;

CREATE INDEX "flatt_actc_idx" ON "wfprev"."file_attachment" ("attachment_content_type_code" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfprev"."file_attachment" ADD CONSTRAINT "flatt_sonc_fk"
	FOREIGN KEY ("source_object_name_code") REFERENCES "wfprev"."source_object_name_code" ("source_object_name_code") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "wfprev"."file_attachment" ADD CONSTRAINT "flatt_actc_fk"
	FOREIGN KEY ("attachment_content_type_code") REFERENCES "wfprev"."attachment_content_type_code" ("attachment_content_type_code") ON DELETE No Action ON UPDATE No Action
;