/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 10-Jan-2025 3:59:20 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."silviculture_method"
(
	"silviculture_method_guid" UUID NOT NULL,    -- silviculture_method_guid is a unique identifier for the record.
	"silviculture_technique_guid" UUID NOT NULL,    -- silviculture_technique_guid: Is a foreign key to silviculture_technique: Silviculture Technique is a list of Silviculture techniques that are mapped to a project type and Silviculture base.
	"silviculture_method_code" varchar(10)	 NOT NULL,    -- silviculture_method_code: Is a foreign key to silviculture_method_code: Silviculture Method Code
	"system_start_timestamp" TIMESTAMP NOT NULL,    -- System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"system_end_timestamp" TIMESTAMP NOT NULL,    -- System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."silviculture_method"
	IS 'Silviculture Method is a list of Silviculture methods that are mapped to a project type and Silviculture technique.  '
;

COMMENT ON COLUMN "wfprev"."silviculture_method"."silviculture_method_guid"
	IS 'silviculture_method_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."silviculture_method"."silviculture_technique_guid"
	IS 'silviculture_technique_guid: Is a foreign key to silviculture_technique: Silviculture Technique is a list of Silviculture techniques that are mapped to a project type and Silviculture base.'
;

COMMENT ON COLUMN "wfprev"."silviculture_method"."silviculture_method_code"
	IS 'silviculture_method_code: Is a foreign key to silviculture_method_code: Silviculture Method Code'
;

COMMENT ON COLUMN "wfprev"."silviculture_method"."system_start_timestamp"
	IS 'System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."silviculture_method"."system_end_timestamp"
	IS 'System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."silviculture_method"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."silviculture_method"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."silviculture_method"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."silviculture_method"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."silviculture_method"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."silviculture_method" ADD CONSTRAINT "slvmethod_pk"
	PRIMARY KEY ("silviculture_method_guid")
;

ALTER TABLE "wfprev"."silviculture_method" ADD CONSTRAINT "slvmethod_uk" UNIQUE ("silviculture_technique_guid","silviculture_method_code","system_start_timestamp","system_end_timestamp")
;

CREATE INDEX "slvmethod_slvtech_idx" ON "wfprev"."silviculture_method" ("silviculture_technique_guid" ASC)
;

CREATE INDEX "slvmethod_slvmthdcd_idx" ON "wfprev"."silviculture_method" ("silviculture_method_code" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfprev"."silviculture_method" ADD CONSTRAINT "slvmethod_slvtech_fk"
	FOREIGN KEY ("silviculture_technique_guid") REFERENCES "wfprev"."silviculture_technique" ("silviculture_technique_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "wfprev"."silviculture_method" ADD CONSTRAINT "slvmethod_slvmthdcd_fk"
	FOREIGN KEY ("silviculture_method_code") REFERENCES "wfprev"."silviculture_method_code" ("silviculture_method_code") ON DELETE No Action ON UPDATE No Action
;