/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 07-Jan-2025 11:21:46 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."silviculture_technique_code"
(
	"silviculture_technique_code" varchar(10)	 NOT NULL,    -- silviculture_technique_code: Silviculture Technique Code is a list of Silviculture techniques that can be applied as a treatment activity.  Taken from THE.SILV_TECHNIQUE_CODE values are:  AE	Aerial BI	Biological BL	Backlog Silviculture Prescription BR	Brushing BU	Burn CA	Chemical Air CB	Climb CC	Cone Collection CG	Chemical Ground CL	Road Clearing CS	Cone Survey CT	Commercial Thinning DD	Site Deg/Disturbance DE	Deactivation DR	Drainage FE	Fertilization FG	Free Growing FH	Forest Health FI	Fire FN	Forest Nutrient FP	Fill Planting GR	Ground GS	Grass Seeding HV	Harvest HZ	Hazard JS	Juvenile Spacing MA	Manual ME	Mechanical MS	Mineral Soil Disturbance NA	Natural OF	Office Review OG	Organic Ground (e.g. sewage sludge, fish mort, pulp sludge, et c.) PA	Pay PH	Pre-Harvest Silviculture Prescription PL	Planting PO	Post Harvest Inspection PR	Pruning RA	Regeneration Performance Assessment RE	Reconnaissance RG	Regen/Stocking RO	Roadside RP	Re-Planting RR	Road Rehab RT	Root Rot SE	Seedling Protection SI	Silviculture Prescription SL	Slide SM	Stand Management Prescription SP	Site Preparation SR	Site Rehabilitation SU	Survival SX	Silviculture Trials TP	Trapping TR	Traverse UP	Road Upgrading WT	Wildlife Tree
	"description" varchar(200)	 NOT NULL,    -- DESCRIPTION is the display quality description of the code value.
	"display_order" decimal(3) NULL,    -- DISPLAY ORDER is to allow non alphabetic sorting e.g. M T W Th F S S.
	"effective_date" DATE NOT NULL DEFAULT CURRENT_DATE,    -- EFFECTIVE_DATE is the date code value becomes effective.
	"expiry_date" DATE NOT NULL DEFAULT '9999-12-31',    -- EXPIRY_DATE is the date code value expires.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."silviculture_technique_code"
	IS 'Silviculture Technique Code is a list of Silviculture techniques that can be applied as a treatment activity.  Taken from THE.SILV_TECHNIQUE_CODE values are:  AE	Aerial BI	Biological BL	Backlog Silviculture Prescription BR	Brushing BU	Burn CA	Chemical Air CB	Climb CC	Cone Collection CG	Chemical Ground CL	Road Clearing CS	Cone Survey CT	Commercial Thinning DD	Site Deg/Disturbance DE	Deactivation DR	Drainage FE	Fertilization FG	Free Growing FH	Forest Health FI	Fire FN	Forest Nutrient FP	Fill Planting GR	Ground GS	Grass Seeding HV	Harvest HZ	Hazard JS	Juvenile Spacing MA	Manual ME	Mechanical MS	Mineral Soil Disturbance NA	Natural OF	Office Review OG	Organic Ground (e.g. sewage sludge, fish mort, pulp sludge, et c.) PA	Pay PH	Pre-Harvest Silviculture Prescription PL	Planting PO	Post Harvest Inspection PR	Pruning RA	Regeneration Performance Assessment RE	Reconnaissance RG	Regen/Stocking RO	Roadside RP	Re-Planting RR	Road Rehab RT	Root Rot SE	Seedling Protection SI	Silviculture Prescription SL	Slide SM	Stand Management Prescription SP	Site Preparation SR	Site Rehabilitation SU	Survival SX	Silviculture Trials TP	Trapping TR	Traverse UP	Road Upgrading WT	Wildlife Tree'
;

COMMENT ON COLUMN "wfprev"."silviculture_technique_code"."silviculture_technique_code"
	IS 'silviculture_technique_code: Silviculture Technique Code is a list of Silviculture techniques that can be applied as a treatment activity.  Taken from THE.SILV_TECHNIQUE_CODE values are:  AE	Aerial BI	Biological BL	Backlog Silviculture Prescription BR	Brushing BU	Burn CA	Chemical Air CB	Climb CC	Cone Collection CG	Chemical Ground CL	Road Clearing CS	Cone Survey CT	Commercial Thinning DD	Site Deg/Disturbance DE	Deactivation DR	Drainage FE	Fertilization FG	Free Growing FH	Forest Health FI	Fire FN	Forest Nutrient FP	Fill Planting GR	Ground GS	Grass Seeding HV	Harvest HZ	Hazard JS	Juvenile Spacing MA	Manual ME	Mechanical MS	Mineral Soil Disturbance NA	Natural OF	Office Review OG	Organic Ground (e.g. sewage sludge, fish mort, pulp sludge, et c.) PA	Pay PH	Pre-Harvest Silviculture Prescription PL	Planting PO	Post Harvest Inspection PR	Pruning RA	Regeneration Performance Assessment RE	Reconnaissance RG	Regen/Stocking RO	Roadside RP	Re-Planting RR	Road Rehab RT	Root Rot SE	Seedling Protection SI	Silviculture Prescription SL	Slide SM	Stand Management Prescription SP	Site Preparation SR	Site Rehabilitation SU	Survival SX	Silviculture Trials TP	Trapping TR	Traverse UP	Road Upgrading WT	Wildlife Tree'
;

COMMENT ON COLUMN "wfprev"."silviculture_technique_code"."description"
	IS 'DESCRIPTION is the display quality description of the code value.'
;

COMMENT ON COLUMN "wfprev"."silviculture_technique_code"."display_order"
	IS 'DISPLAY ORDER is to allow non alphabetic sorting e.g. M T W Th F S S.'
;

COMMENT ON COLUMN "wfprev"."silviculture_technique_code"."effective_date"
	IS 'EFFECTIVE_DATE is the date code value becomes effective.'
;

COMMENT ON COLUMN "wfprev"."silviculture_technique_code"."expiry_date"
	IS 'EXPIRY_DATE is the date code value expires.'
;

COMMENT ON COLUMN "wfprev"."silviculture_technique_code"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."silviculture_technique_code"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."silviculture_technique_code"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."silviculture_technique_code"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."silviculture_technique_code"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."silviculture_technique_code" ADD CONSTRAINT "slvtchcd_pk"
	PRIMARY KEY ("silviculture_technique_code")
;