/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 08-Jan-2025 11:26:50 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."activity_boundary"
(
	"activity_boundary_guid" UUID NOT NULL,    -- activity_boundary_guid is a unique identifier for the record.
	"activity_guid" UUID NOT NULL,    -- activity_guid: Is a foreign key to activity: Activity is used to track the treatment activities that are planned for the project for the fiscal year.
	"system_start_timestamp" TIMESTAMP NOT NULL,    -- System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"system_end_timestamp" TIMESTAMP NOT NULL,    -- System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"mapping_label" varchar(250)	 NULL,    -- Mapping Label is a label assigned to the polygon for downstream mapping purposes.
	"collection_date" DATE NOT NULL,    -- Collection Date is the date that the polygon was originally captured/created.
	"collection_method" varchar(4000)	 NULL,    -- Collection Method describes the method used to collect the Geometry data.
	"collector_name" varchar(100)	 NULL,    -- Collector Name is the name of the person who established  the project boundary polygon. 
	"boundary_size_ha" decimal(19,4) NOT NULL,    -- Incident Size Ha is the size of the project measured in hectares, to three decimals (e.g., 0.001).
	"boundary_comment" varchar(2000)	 NULL,    -- Boundary Comment provides additional information related to the collection of the polygon data.
	"geometry" POLYGON NOT NULL,    -- Geometry is the geographic area that is the boundary of the project.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."activity_boundary"
	IS 'Activity Boundary is a point-in-time capture of the boundary area of an activity.   Boundaries are maintained in a desktop GIS tool and uploaded to WF1.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."activity_boundary_guid"
	IS 'activity_boundary_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."activity_guid"
	IS 'activity_guid: Is a foreign key to activity: Activity is used to track the treatment activities that are planned for the project for the fiscal year.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."system_start_timestamp"
	IS 'System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."system_end_timestamp"
	IS 'System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."mapping_label"
	IS 'Mapping Label is a label assigned to the polygon for downstream mapping purposes.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."collection_date"
	IS 'Collection Date is the date that the polygon was originally captured/created.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."collection_method"
	IS 'Collection Method describes the method used to collect the Geometry data.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."collector_name"
	IS 'Collector Name is the name of the person who established  the project boundary polygon. '
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."boundary_size_ha"
	IS 'Incident Size Ha is the size of the project measured in hectares, to three decimals (e.g., 0.001).'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."boundary_comment"
	IS 'Boundary Comment provides additional information related to the collection of the polygon data.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."geometry"
	IS 'Geometry is the geographic area that is the boundary of the project.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."activity_boundary"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."activity_boundary" ADD CONSTRAINT "actbnd_pk"
	PRIMARY KEY ("activity_boundary_guid")
;

ALTER TABLE "wfprev"."activity_boundary" ADD CONSTRAINT "actbnd_uk" UNIQUE ("activity_guid","system_start_timestamp","system_end_timestamp")
;

CREATE INDEX "actbnd_actvty_idx" ON "wfprev"."activity_boundary" ("activity_guid" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfprev"."activity_boundary" ADD CONSTRAINT "actbnd_actvty_fk"
	FOREIGN KEY ("activity_guid") REFERENCES "wfprev"."activity" ("activity_guid") ON DELETE No Action ON UPDATE No Action
;