/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-Dec-2024 2:27:41 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."fuel_mgmt_plan_obj_xref"
(
	"fuel_mgmt_plan_obj_xref_guid" UUID NOT NULL,    -- fuel_mgmt_plan_obj_xref_guid is a unique identifier for the record.
	"fuel_management_project_guid" UUID NOT NULL,    -- fuel_management_project_guid: Is a foreign key to fuel_management_project: Fuel Management Project is used to track project attributes specific to Fuel Management, such as Coarse, Medium, and Fine Filters.  The project is evaluated for the objectives that will be accomplished by the project. Each objective has a value, the sum of the objective values produces an objective score for the project.  Projects with a high score will get preference for funding.
	"fuel_management_objective_guid" UUID NOT NULL,    -- fuel_management_objective_guid: Is a foreign key to fuel_management_objective: Fuel Management Objective is a set of ranked objective that can be associated to a Fuel Management Request.  The objectives are broken into categories, such as project alignment with government objectives and project level objectives.  The objectives are ranked by importance. A project will receive a project alignment score for each objective category which is used to rank the importance of a project.  Government Alignment Objectives are: 12 - Treatment with several TUs moving onto next Unit11 - Adjacent Fule Management Treatments, or new TU with Rx 10 - Prescription Complete - Next phase is treatment 9 - Tactical Plan Complete - New Phase Rx Development 8 - Mitigates Risk around or adjacent to Critical Infrastructure incl Watersheds 7 - Improve Egress/Evac Routes 6 - Maximize Funding Linkages 5 - Supports Reconciliation with Indigenous peoples  Project Levels Objectives are: 4 - PSTA Class Greater than 7 3 - Part of Larger Risk Reduction Strategy 2 - Cost Effectiveness 1 - WUI WRR Plans with AOI that expands outside of the WUI
	"system_start_timestamp" TIMESTAMP NOT NULL,    -- System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"system_end_timestamp" TIMESTAMP NOT NULL,    -- System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"objective_selected_ind" boolean NOT NULL DEFAULT 'N',    -- Objective Selected Ind indicates whether the objective mapped to the Fuel Management Request is selected (Y) or not (N).  If true then the weighted rank of the objective will count against the filter score.  If false then a value of 0 will be counted against the filter score.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."fuel_mgmt_plan_obj_xref"
	IS 'Fuel Management Plan Objective Xref is used to track objectives that are intended to be accomplished by a Fuel Management Project Fiscal Plan.'
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."fuel_mgmt_plan_obj_xref_guid"
	IS 'fuel_mgmt_plan_obj_xref_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."fuel_management_project_guid"
	IS 'fuel_management_project_guid: Is a foreign key to fuel_management_project: Fuel Management Project is used to track project attributes specific to Fuel Management, such as Coarse, Medium, and Fine Filters.  The project is evaluated for the objectives that will be accomplished by the project. Each objective has a value, the sum of the objective values produces an objective score for the project.  Projects with a high score will get preference for funding.'
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."fuel_management_objective_guid"
	IS 'fuel_management_objective_guid: Is a foreign key to fuel_management_objective: Fuel Management Objective is a set of ranked objective that can be associated to a Fuel Management Request.  The objectives are broken into categories, such as project alignment with government objectives and project level objectives.  The objectives are ranked by importance. A project will receive a project alignment score for each objective category which is used to rank the importance of a project.  Government Alignment Objectives are: 12 - Treatment with several TUs moving onto next Unit11 - Adjacent Fule Management Treatments, or new TU with Rx 10 - Prescription Complete - Next phase is treatment 9 - Tactical Plan Complete - New Phase Rx Development 8 - Mitigates Risk around or adjacent to Critical Infrastructure incl Watersheds 7 - Improve Egress/Evac Routes 6 - Maximize Funding Linkages 5 - Supports Reconciliation with Indigenous peoples  Project Levels Objectives are: 4 - PSTA Class Greater than 7 3 - Part of Larger Risk Reduction Strategy 2 - Cost Effectiveness 1 - WUI WRR Plans with AOI that expands outside of the WUI'
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."system_start_timestamp"
	IS 'System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."system_end_timestamp"
	IS 'System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."objective_selected_ind"
	IS 'Objective Selected Ind indicates whether the objective mapped to the Fuel Management Request is selected (Y) or not (N).  If true then the weighted rank of the objective will count against the filter score.  If false then a value of 0 will be counted against the filter score.'
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."fuel_mgmt_plan_obj_xref"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."fuel_mgmt_plan_obj_xref" ADD CONSTRAINT "fmpobjx_pk"
	PRIMARY KEY ("fuel_mgmt_plan_obj_xref_guid")
;

ALTER TABLE "wfprev"."fuel_mgmt_plan_obj_xref" ADD CONSTRAINT "fmpobjx_uk" UNIQUE ("fuel_management_project_guid","fuel_management_objective_guid","system_start_timestamp","system_end_timestamp")
;

CREATE INDEX "fmpobjx_fmprj_idx" ON "wfprev"."fuel_mgmt_plan_obj_xref" ("fuel_management_project_guid" ASC)
;

CREATE INDEX "fmpobjx_fmobj_idx" ON "wfprev"."fuel_mgmt_plan_obj_xref" ("fuel_management_objective_guid" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfprev"."fuel_mgmt_plan_obj_xref" ADD CONSTRAINT "fmpobjx_fmprj_fk"
	FOREIGN KEY ("fuel_management_project_guid") REFERENCES "wfprev"."fuel_management_project" ("fuel_management_project_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "wfprev"."fuel_mgmt_plan_obj_xref" ADD CONSTRAINT "fmpobjx_fmobj_fk"
	FOREIGN KEY ("fuel_management_objective_guid") REFERENCES "wfprev"."fuel_management_objective" ("fuel_management_objective_guid") ON DELETE No Action ON UPDATE No Action
;