/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-Dec-2024 11:33:56 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."fuel_management_objective"
(
	"fuel_management_objective_guid" UUID NOT NULL,    -- fuel_management_objective_guid is a unique identifier for the record.
	"fuel_mgmt_obj_type_code" varchar(10)	 NOT NULL,    -- fuel_mgmt_obj_type_code: Is a foreign key to fuel_mgmt_obj_type_code: Fuel Management Objective Type Code defines the types of objectives that are available for a Fuel Management Request.  Values are:  	- Government Objective 	- Project Level Objective
	"objective_label" varchar(300)	 NOT NULL,    -- Objective Label is a brief statement of a fire prevention objective.
	"system_start_timestamp" TIMESTAMP NOT NULL,    -- System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"system_end_timestamp" TIMESTAMP NOT NULL,    -- System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. 
	"weighted_rank" decimal(3) NOT NULL,    -- Weighted Rank is a rank assigned to an objective. Every objective has a rank, and that rank is weighted.  No two objectives have the same weighted rank. The current weighted ranks range from 1 (lowest rank) to 12 (highest rank).
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."fuel_management_objective"
	IS 'Fuel Management Objective is a set of ranked objective that can be associated to a Fuel Management Request.  The objectives are broken into categories, such as project alignment with government objectives and project level objectives.  The objectives are ranked by importance. A project will receive a project alignment score for each objective category which is used to rank the importance of a project.  Government Alignment Objectives are: 12 - Treatment with several TUs moving onto next Unit11 - Adjacent Fule Management Treatments, or new TU with Rx 10 - Prescription Complete - Next phase is treatment 9 - Tactical Plan Complete - New Phase Rx Development 8 - Mitigates Risk around or adjacent to Critical Infrastructure incl Watersheds 7 - Improve Egress/Evac Routes 6 - Maximize Funding Linkages 5 - Supports Reconciliation with Indigenous peoples  Project Levels Objectives are: 4 - PSTA Class Greater than 7 3 - Part of Larger Risk Reduction Strategy 2 - Cost Effectiveness 1 - WUI WRR Plans with AOI that expands outside of the WUI'
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."fuel_management_objective_guid"
	IS 'fuel_management_objective_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."fuel_mgmt_obj_type_code"
	IS 'fuel_mgmt_obj_type_code: Is a foreign key to fuel_mgmt_obj_type_code: Fuel Management Objective Type Code defines the types of objectives that are available for a Fuel Management Request.  Values are:  	- Government Objective 	- Project Level Objective'
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."objective_label"
	IS 'Objective Label is a brief statement of a fire prevention objective.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."system_start_timestamp"
	IS 'System Start Timestamp is the date and time with millisecond accuracy when the record becomes effective.   The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."system_end_timestamp"
	IS 'System End Timestamp is the date and time with millisecond accuracy when the record becomes effective. The current instance of the record will be set to Dec 31, 9999 by default.  The System Start Timestamp and System End Timestamp fields are managed as a set by the system and is not exposed to the end user. When an update is made to the data in the record, the system will be responsible for expiring the old record and creating a new record with the updated data. '
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."weighted_rank"
	IS 'Weighted Rank is a rank assigned to an objective. Every objective has a rank, and that rank is weighted.  No two objectives have the same weighted rank. The current weighted ranks range from 1 (lowest rank) to 12 (highest rank).'
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."fuel_management_objective"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."fuel_management_objective" ADD CONSTRAINT "fmobj_pk"
	PRIMARY KEY ("fuel_management_objective_guid")
;

ALTER TABLE "wfprev"."fuel_management_objective" ADD CONSTRAINT "fmobj_uk" UNIQUE ("fuel_mgmt_obj_type_code","objective_label","system_start_timestamp","system_end_timestamp")
;

CREATE INDEX "fmobj_fmotc_idx" ON "wfprev"."fuel_management_objective" ("fuel_mgmt_obj_type_code" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "wfprev"."fuel_management_objective" ADD CONSTRAINT "fmobj_fmotc_fk"
	FOREIGN KEY ("fuel_mgmt_obj_type_code") REFERENCES "wfprev"."fuel_mgmt_obj_type_code" ("fuel_mgmt_obj_type_code") ON DELETE No Action ON UPDATE No Action
;