import { Injectable, inject } from '@angular/core';
import { TokenService } from './token.service';

export const WFPREV_ACTIONS = {
  GET_TOPLEVEL:                 'WFPREV.GET_TOPLEVEL',
  GET_PREVENTION_PROJECT:       'WFPREV.GET_PREVENTION_PROJECT',
  CREATE_PREVENTION_PROJECT:    'WFPREV.CREATE_PREVENTION_PROJECT',
  UPDATE_PREVENTION_PROJECT:    'WFPREV.UPDATE_PREVENTION_PROJECT',
  DELETE_PREVENTION_PROJECT:    'WFPREV.DELETE_PREVENTION_PROJECT',
  CREATE_PREVENTION_FISCAL:     'WFPREV.CREATE_PREVENTION_FISCAL',
  UPDATE_PREVENTION_FISCAL:     'WFPREV.UPDATE_PREVENTION_FISCAL',
  DELETE_PREVENTION_FISCAL:     'WFPREV.DELETE_PREVENTION_FISCAL',
  CREATE_PREVENTION_ACTIVITY:   'WFPREV.CREATE_PREVENTION_ACTIVITY',
  UPDATE_PREVENTION_ACTIVITY:   'WFPREV.UPDATE_PREVENTION_ACTIVITY',
  DELETE_PREVENTION_ACTIVITY:   'WFPREV.DELETE_PREVENTION_ACTIVITY',
  CREATE_PERFORMANCE_UPDATE:    'WFPREV.CREATE_PERFORMANCE_UPDATE',
  CREATE_SPATIAL_UPLOAD:        'WFPREV.CREATE_SPATIAL_UPLOAD',
  DELETE_SPATIAL_UPLOAD:        'WFPREV.DELETE_SPATIAL_UPLOAD',
  UPDATE_SPATIAL_METADATA:      'WFPREV.UPDATE_SPATIAL_METADATA',
  GET_SPATIAL:                  'WFPREV.GET_SPATIAL',
  EXPORT_TO_RESULTS:            'WFPREV.EXPORT_TO_RESULTS',
  CREATE_EVALUATION_CRITERIA:   'WFPREV.CREATE_EVALUATION_CRITERIA',
  UPDATE_EVALUATION_CRITERIA:   'WFPREV.UPDATE_EVALUATION_CRITERIA',
  DELETE_EVALUATION_CRITERIA:   'WFPREV.DELETE_EVALUATION_CRITERIA',
  CREATE_YEAR_END_REPORT:       'WFPREV.CREATE_YEAR_END_REPORT',
  UPDATE_YEAR_END_REPORT:       'WFPREV.UPDATE_YEAR_END_REPORT',
  DELETE_YEAR_END_REPORT:       'WFPREV.DELETE_YEAR_END_REPORT',
  CREATE_ACTIVITY_ATTACHMENT:   'WFPREV.CREATE_ACTIVITY_ATTACHMENT',
  UPDATE_ACTIVITY_ATTACHMENT:   'WFPREV.UPDATE_ACTIVITY_ATTACHMENT',
  DELETE_ACTIVITY_ATTACHMENT:   'WFPREV.DELETE_ACTIVITY_ATTACHMENT',
} as const;

export type WfprevAction = (typeof WFPREV_ACTIONS)[keyof typeof WFPREV_ACTIONS];

@Injectable({ providedIn: 'root' })
export class PermissionsService {
  private readonly tokenService = inject(TokenService);

  hasAction(action: WfprevAction): boolean {
    return this.tokenService.doesUserHaveApplicationPermissions([action]);
  }
}