/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 20-Dec-2024 4:08:25 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."ancillary_funding_source"
(
	"ancillary_funding_source_guid" UUID NOT NULL,    -- ancillary_funding_source_guid is a unique identifier for the record.
	"funding_source_abbreviation" varchar(20)	 NOT NULL,    -- Funding Source Abbreviation is the abbreviation used to identify a funding source.
	"funding_source_name" varchar(50)	 NOT NULL,    -- Funding Source Name is the full display name of a funding source.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "wfprev"."ancillary_funding_source"
	IS 'Ancillary Funding Source is a list of ancillary funding providers who may provide additional funds on top of what is provided by a primary funding provider to complete a treatment.  Example Funding Sources:  	- BCP - BC Parks 	- CFS - FireSmart Community Funding Supports   	- CLWRR - Crown Land Wildfire Risk Reduction 	- Community Resiliency Investment   	- FEP - Forest Employment Program 	- FESBC - Forest Enhancement Society of BC 	- ER - Ecosytem Restoration   	- Forest District Org Unit'
;

COMMENT ON COLUMN "wfprev"."ancillary_funding_source"."ancillary_funding_source_guid"
	IS 'ancillary_funding_source_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."ancillary_funding_source"."funding_source_abbreviation"
	IS 'Funding Source Abbreviation is the abbreviation used to identify a funding source.'
;

COMMENT ON COLUMN "wfprev"."ancillary_funding_source"."funding_source_name"
	IS 'Funding Source Name is the full display name of a funding source.'
;

COMMENT ON COLUMN "wfprev"."ancillary_funding_source"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."ancillary_funding_source"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."ancillary_funding_source"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."ancillary_funding_source"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."ancillary_funding_source"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."ancillary_funding_source" ADD CONSTRAINT "afsrc_pk"
	PRIMARY KEY ("ancillary_funding_source_guid")
;