/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 15-May-2026 2:26:01 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "wfprev"."project_plan_fiscal_closeout_audit"
(
	"audit_table_sequence" decimal(15) NOT NULL,    -- Added by transform - intent is make this sequence noncached so order is maintained
	"audit_action_code" varchar(10)	 NOT NULL,    -- Contains the reason the audit record is written - Insert/Update/Delete/Conversion
	"project_plan_fiscal_closeout_guid" UUID NULL,    -- project_plan_fiscal_closeout_guid is a unique identifier for the record.
	"project_plan_fiscal_guid" UUID NOT NULL,    -- project_plan_fiscal_guid: Is a foreign key to project_plan_fiscal: Project Plan Fiscal is used to store a plan for the work to be done in a fiscal year for the project. 
	"outcome_comment" varchar(4000)	 NOT NULL,    -- Outcome Comment is used to document the final outcomes and comments for the fiscal year close-out.
	"revision_count" decimal(10) NOT NULL DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64)	 NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64)	 NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_closeout_audit"."audit_table_sequence"
	IS 'Added by transform - intent is make this sequence noncached so order is maintained'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_closeout_audit"."audit_action_code"
	IS 'Contains the reason the audit record is written - Insert/Update/Delete/Conversion'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_closeout_audit"."project_plan_fiscal_closeout_guid"
	IS 'project_plan_fiscal_closeout_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_closeout_audit"."project_plan_fiscal_guid"
	IS 'project_plan_fiscal_guid: Is a foreign key to project_plan_fiscal: Project Plan Fiscal is used to store a plan for the work to be done in a fiscal year for the project. '
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_closeout_audit"."outcome_comment"
	IS 'Outcome Comment is used to document the final outcomes and comments for the fiscal year close-out.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_closeout_audit"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_closeout_audit"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_closeout_audit"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_closeout_audit"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "wfprev"."project_plan_fiscal_closeout_audit"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "wfprev"."project_plan_fiscal_closeout_audit" ADD CONSTRAINT "ppfyco_aud_pk"
	PRIMARY KEY ("audit_table_sequence")
;