env:
  IMAGE_NAME: "${{ github.repository }}-${{inputs.PROJECT_NAME}}"
  NPMRC: ${{ secrets.NPMRC }}

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      TAG:
        type: string
        description: Additional tag to add to built images

jobs: 
  wfprev-ui:
    uses: ./.github/workflows/mvn-build.yml
    secrets: inherit
    with:
      PROJECT_NAME: wfprev-ui
      TAG: ${{inputs.TAG}}
      PROJECT_TYPE: frontend
