env:
  IMAGE_NAME: "${{ github.repository }}-${{inputs.PROJECT_NAME}}"
  NPMRC: ${{ secrets.NPMRC }}

permissions:
  contents: read
  packages: write
  id-token: write

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - ".github/workflows/**"
      - "client/**"
      - "server/**"
      - "db/**"
      - "!**/README.md"
      - 'lambda/report-generator/**'
  workflow_dispatch:
    inputs:
      TAG:
        type: string
        description: Additional tag to add to built images

jobs: 
  node-build:
    uses: ./.github/workflows/node-build.yml
    secrets: inherit
    with:
      COMPONENT_NAME: wfprev-gdb-extractor
      TAG: latest

  wfprev-api:
    uses: ./.github/workflows/mvn-build.yml
    secrets: inherit
    with:
      COMPONENT_NAME: wfprev-api
      TAG: latest
      COMPONENT_TYPE: server
  
  liquibase-build:
    uses: ./.github/workflows/liquibase-build.yml
    secrets: inherit
    with:
      TAG: latest

  report-generator-lambda:
    uses: ./.github/workflows/lambda-build.yml
    secrets: inherit

  terragrunt-deploy-dev:
    uses: ./.github/workflows/terragrunt-deploy.yml
    needs: [node-build, wfprev-api, liquibase-build, report-generator-lambda]
    with:
      DEFAULT_APPLICATION_ENVIRONMENT: dev
      IMAGE_TAG: latest
      RUN_LIQUIBASE: true
      COMMAND: apply
      GDB_EXTRACTOR_DIGEST: ${{ needs.node-build.outputs.gdb_digest }}
    secrets: inherit

  wfprev-ui:
    uses: ./.github/workflows/client-build.yml
    needs: [terragrunt-deploy-dev]
    with:
      DEFAULT_APPLICATION_ENVIRONMENT: dev
    secrets: inherit
    
