permissions:
  contents: read
  packages: write
  id-token: write

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'
      - 'feature/lza-migration'
    paths:
      - ".github/workflows/**"
      - "client/**"
      - "server/**"
      - "terraform/**"
      - "db/**"
      - "!**/README.md"
      - 'lambda/report-generator/**'
  workflow_dispatch:

jobs: 
  node-build:
    uses: ./.github/workflows/node-build.yml
    secrets: inherit
    with:
      COMPONENT_NAME: wfprev-gdb-extractor
      TAG: latest

  wfprev-api:
    uses: ./.github/workflows/mvn-build.yml
    secrets: inherit
    with:
      COMPONENT_NAME: wfprev-api
      TAG: latest
      COMPONENT_TYPE: server
  
  liquibase-build:
    uses: ./.github/workflows/liquibase-build.yml
    secrets: inherit
    with:
      TAG: latest

  report-generator-lambda:
    uses: ./.github/workflows/lambda-build.yml
    secrets: inherit
      
  terragrunt-deploy-wfint:
    uses: ./.github/workflows/terragrunt-deploy.yml
    needs: [node-build, wfprev-api, liquibase-build, report-generator-lambda]
    with:
      DEFAULT_APPLICATION_ENVIRONMENT: wfint
      IMAGE_TAG: latest
      RUN_LIQUIBASE: true
      COMMAND: apply
    secrets: inherit

  wfprev-ui:
    uses: ./.github/workflows/client-build.yml
    needs: [terragrunt-deploy-wfint]
    with:
      DEFAULT_APPLICATION_ENVIRONMENT: wfint
    secrets: inherit
    
