name: SonarScan

env: 
  NPMRC: ${{ secrets.NPMRC }}

on:
  push:
    branches: [ main, feature/* ]
  pull_request_target:
    branches: [ main, feature/* ] 

jobs:
  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4   
        with:
          java-version: 17
          distribution: 'adopt' 
      - name: SonarCloud Scan 
        run: |          
            export MAVEN_OPTS="-Xmx10000m"
            export NODE_OPTIONS="--max-old-space-size=4096"
            mvn clean --settings server/wfprev-api/mvn_settings/settings.xml -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bcgov_nr-bcws-wfprev -Drepo.login=${{ secrets.IDIR_AS_EMAIL }} -Drepo.password=${{ secrets.IDIR_PASSWORD }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
