name: SonarScan

env: 
  NPMRC: ${{ secrets.NPMRC }}

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  test:
    name: Test - Unit and Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      #- name: Maven Verify
        #run: mvn -B clean verify

  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt' 
      - name: SonarCloud Scan
        run: mvn -B clean verify -Pcoverage,sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
